import type { LearningCompetency } from "@/content/learning-architecture-types";

export const ce1Competencies = [
  {
    id: "ce1-fr-edl-reconnaitre-phrase",
    slug: "reconnaitre-une-phrase",
    levelSlug: "ce1",
    subject: "Français",
    domainSlug: "francais",
    subdomainSlug: "etude-de-la-langue",
    title: "Reconnaître une phrase",
    observableObjective:
      "Distinguer une phrase correcte d'un groupe de mots incomplet.",
    successCriteria: [
      "Je vérifie que les mots ont du sens ensemble.",
      "Je repère la majuscule au début.",
      "Je repère la ponctuation finale.",
    ],
    lessonIds: ["ce1-fr-gram-phrase"],
    guideCharacter: {
      characterSlug: "gaston",
      name: "Gaston",
    },
    status: "in-progress",
    sequence: {
      id: "seq-ce1-fr-edl-reconnaitre-phrase",
      competencyId: "ce1-fr-edl-reconnaitre-phrase",
      title: "Observer la phrase en 5 temps",
      status: "in-progress",
      steps: [
        {
          id: "seq-ce1-fr-edl-reconnaitre-phrase-1",
          order: 1,
          kind: "discovery",
          title: "Comparer phrase et groupe de mots",
          objective: "Repérer ce qui permet de reconnaître une phrase.",
          status: "in-progress",
        },
        {
          id: "seq-ce1-fr-edl-reconnaitre-phrase-3",
          order: 3,
          kind: "guided-practice",
          title: "Classer des exemples",
          objective: "Utiliser les critères avec un guidage.",
          status: "upcoming",
        },
        {
          id: "seq-ce1-fr-edl-reconnaitre-phrase-5",
          order: 5,
          kind: "assessment",
          title: "Identifier seul",
          objective: "Justifier pourquoi une proposition est une phrase.",
          status: "upcoming",
        },
      ],
    },
  },
  {
    id: "ce1-fr-lc-informations-explicites",
    slug: "identifier-les-informations-explicites-dun-texte-court",
    levelSlug: "ce1",
    subject: "Français",
    domainSlug: "francais",
    subdomainSlug: "lecture-comprehension",
    title: "Identifier les informations explicites d'un texte court",
    observableObjective:
      "Repérer les personnages, lieux ou actions indiqués directement.",
    successCriteria: [
      "Je retrouve une information écrite dans le texte.",
      "Je réponds avec des mots du texte.",
      "Je vérifie ma réponse en relisant.",
    ],
    lessonIds: [],
    status: "upcoming",
    sequence: {
      id: "seq-ce1-fr-lc-informations-explicites",
      competencyId: "ce1-fr-lc-informations-explicites",
      title: "Chercher l'information écrite",
      status: "upcoming",
      steps: [],
    },
  },
  {
    id: "ce1-fr-ecr-phrases-coherentes",
    slug: "ecrire-quelques-phrases-coherentes",
    levelSlug: "ce1",
    subject: "Français",
    domainSlug: "francais",
    subdomainSlug: "ecriture",
    title: "Écrire quelques phrases cohérentes",
    observableObjective:
      "Rédiger deux ou trois phrases qui répondent à une consigne simple.",
    successCriteria: [
      "Mes phrases parlent du sujet demandé.",
      "Chaque phrase a du sens.",
      "Je mets les majuscules et les points.",
    ],
    lessonIds: [],
    status: "upcoming",
    sequence: {
      id: "seq-ce1-fr-ecr-phrases-coherentes",
      competencyId: "ce1-fr-ecr-phrases-coherentes",
      title: "Écrire court et clair",
      status: "upcoming",
      steps: [],
    },
  },
  {
    id: "ce1-fr-edl-identifier-sujet-verbe",
    slug: "identifier-le-verbe-et-son-sujet",
    levelSlug: "ce1",
    subject: "Français",
    domainSlug: "francais",
    subdomainSlug: "etude-de-la-langue",
    title: "Identifier le verbe et son sujet",
    observableObjective:
      "Repérer le verbe conjugué et le sujet dans une phrase simple.",
    successCriteria: [
      "Je trouve le mot qui indique l'action.",
      "Je demande qui fait l'action.",
      "Je relie le sujet au verbe.",
    ],
    lessonIds: [],
    status: "upcoming",
    sequence: {
      id: "seq-ce1-fr-edl-identifier-sujet-verbe",
      competencyId: "ce1-fr-edl-identifier-sujet-verbe",
      title: "Qui fait quoi ?",
      status: "upcoming",
      steps: [],
    },
  },
  {
    id: "ce1-ma-cal-soustraire-centaine",
    slug: "soustraire-dans-la-centaine",
    levelSlug: "ce1",
    subject: "Mathématiques",
    domainSlug: "mathematiques",
    subdomainSlug: "calcul",
    title: "Soustraire dans la centaine",
    observableObjective:
      "Calculer une soustraction simple avec une stratégie adaptée.",
    successCriteria: [
      "Je comprends ce qu'il faut enlever ou comparer.",
      "Je choisis une stratégie de calcul.",
      "Je vérifie que le résultat est possible.",
    ],
    lessonIds: [],
    status: "upcoming",
    sequence: {
      id: "seq-ce1-ma-cal-soustraire-centaine",
      competencyId: "ce1-ma-cal-soustraire-centaine",
      title: "Soustraire avec méthode",
      status: "upcoming",
      steps: [],
    },
  },
  {
    id: "ce1-ma-prob-additifs-une-etape",
    slug: "resoudre-un-probleme-additif-en-une-etape",
    levelSlug: "ce1",
    subject: "Mathématiques",
    domainSlug: "mathematiques",
    subdomainSlug: "problemes",
    title: "Résoudre un problème additif en une étape",
    observableObjective:
      "Choisir addition ou soustraction pour résoudre une situation courte.",
    successCriteria: [
      "Je repère ce qu'on cherche.",
      "Je choisis l'opération adaptée.",
      "J'écris une réponse courte.",
    ],
    lessonIds: [],
    status: "upcoming",
    sequence: {
      id: "seq-ce1-ma-prob-additifs-une-etape",
      competencyId: "ce1-ma-prob-additifs-une-etape",
      title: "Choisir et répondre",
      status: "upcoming",
      steps: [],
    },
  },
  {
    id: "ce1-fr-oral-raconter-evenement-bref",
    slug: "raconter-un-evenement-bref",
    levelSlug: "ce1",
    subject: "Français",
    domainSlug: "francais",
    subdomainSlug: "oral",
    title: "Raconter un événement bref",
    observableObjective:
      "Présenter un fait vécu ou lu dans un ordre compréhensible.",
    successCriteria: [
      "Je dis de qui ou de quoi je parle.",
      "Je respecte l'ordre des événements.",
      "Je parle avec des phrases compréhensibles.",
    ],
    lessonIds: [],
    status: "upcoming",
    sequence: {
      id: "seq-ce1-fr-oral-raconter-evenement-bref",
      competencyId: "ce1-fr-oral-raconter-evenement-bref",
      title: "Raconter dans l'ordre",
      status: "upcoming",
      steps: [],
    },
  },
  {
    id: "ce1-ma-gm-mesurer-longueur",
    slug: "mesurer-une-longueur",
    levelSlug: "ce1",
    subject: "Mathématiques",
    domainSlug: "mathematiques",
    subdomainSlug: "grandeurs-mesures",
    title: "Mesurer une longueur",
    observableObjective:
      "Utiliser la règle graduée pour mesurer un segment simple.",
    successCriteria: [
      "Je place correctement le zéro de la règle.",
      "Je lis la graduation d'arrivée.",
      "J'écris la mesure avec son unité.",
    ],
    lessonIds: [],
    status: "upcoming",
    sequence: {
      id: "seq-ce1-ma-gm-mesurer-longueur",
      competencyId: "ce1-ma-gm-mesurer-longueur",
      title: "Mesurer avec la règle",
      status: "upcoming",
      steps: [],
    },
  },
  {
    id: "ce1-ma-geo-decrire-figures-planes",
    slug: "reconnaitre-et-decrire-des-figures-planes",
    levelSlug: "ce1",
    subject: "Mathématiques",
    domainSlug: "mathematiques",
    subdomainSlug: "geometrie",
    title: "Reconnaître et décrire des figures planes",
    observableObjective:
      "Nommer des figures simples et décrire une propriété visible.",
    successCriteria: [
      "Je nomme la figure reconnue.",
      "Je compte les côtés ou les sommets.",
      "J'utilise un vocabulaire géométrique simple.",
    ],
    lessonIds: [],
    status: "upcoming",
    sequence: {
      id: "seq-ce1-ma-geo-decrire-figures-planes",
      competencyId: "ce1-ma-geo-decrire-figures-planes",
      title: "Nommer et décrire",
      status: "upcoming",
      steps: [],
    },
  },
  {
    id: "ce1-qdm-matiere-etats",
    slug: "distinguer-les-etats-de-la-matiere",
    levelSlug: "ce1",
    subject: "Questionner le monde",
    domainSlug: "questionner-le-monde",
    subdomainSlug: "matiere-objets",
    title: "Distinguer les états solide, liquide et gazeux",
    observableObjective:
      "Classer des substances selon leur état observable.",
    successCriteria: [
      "Je décris ce que j'observe.",
      "Je classe la substance dans le bon état.",
      "Je nomme un changement d'état simple.",
    ],
    lessonIds: [],
    status: "upcoming",
    sequence: {
      id: "seq-ce1-qdm-matiere-etats",
      competencyId: "ce1-qdm-matiere-etats",
      title: "Observer et classer",
      status: "upcoming",
      steps: [],
    },
  },
  {
    id: "ce1-qdm-cycle-eau-simplifie",
    slug: "decrire-le-cycle-de-leau-simplifie",
    levelSlug: "ce1",
    subject: "Questionner le monde",
    domainSlug: "questionner-le-monde",
    subdomainSlug: "matiere-objets",
    title: "Décrire le cycle de l'eau simplifié",
    observableObjective:
      "Relier évaporation, condensation et précipitations à des observations.",
    successCriteria: [
      "Je nomme les étapes principales.",
      "Je les place dans un ordre cohérent.",
      "Je relie une étape à une observation.",
    ],
    lessonIds: [],
    status: "upcoming",
    sequence: {
      id: "seq-ce1-qdm-cycle-eau-simplifie",
      competencyId: "ce1-qdm-cycle-eau-simplifie",
      title: "Suivre le trajet de l'eau",
      status: "upcoming",
      steps: [],
    },
  },
  {
    id: "ce1-fr-lc-retenir-essentiel",
    slug: "retenir-lessentiel-dun-texte-lu",
    levelSlug: "ce1",
    subject: "Français",
    domainSlug: "francais",
    subdomainSlug: "lecture-comprehension",
    title: "Retenir l'essentiel d'un texte lu",
    observableObjective:
      "Résumer en une ou deux phrases ce qu'on vient de lire.",
    successCriteria: [
      "Je retrouve le personnage ou le sujet principal.",
      "Je formule ce qui s'est passé ou ce qu'on a appris.",
      "Je ne recopie pas le texte mot pour mot.",
    ],
    lessonIds: [],
    status: "upcoming",
    sequence: {
      id: "seq-ce1-fr-lc-retenir-essentiel",
      competencyId: "ce1-fr-lc-retenir-essentiel",
      title: "Dire ce qu'on a retenu",
      status: "upcoming",
      steps: [],
    },
  },
  {
    id: "ce1-fr-orth-accorder-determinant",
    slug: "accorder-le-determinant-avec-le-nom",
    levelSlug: "ce1",
    subject: "Français",
    domainSlug: "francais",
    subdomainSlug: "orthographe",
    title: "Accorder le déterminant avec le nom",
    observableObjective:
      "Choisir le bon article selon le genre et le nombre du nom.",
    successCriteria: [
      "Je repère le nom dans le groupe nominal.",
      "Je choisis le déterminant adapté au genre.",
      "Je marque le pluriel sur le déterminant si nécessaire.",
    ],
    lessonIds: [],
    status: "upcoming",
    sequence: {
      id: "seq-ce1-fr-orth-accorder-determinant",
      competencyId: "ce1-fr-orth-accorder-determinant",
      title: "Choisir le bon déterminant",
      status: "upcoming",
      steps: [],
    },
  },
  {
    id: "ce1-fr-orth-marquer-pluriel",
    slug: "marquer-le-pluriel-des-noms",
    levelSlug: "ce1",
    subject: "Français",
    domainSlug: "francais",
    subdomainSlug: "orthographe",
    title: "Marquer le pluriel des noms",
    observableObjective:
      "Ajouter -s au nom et au déterminant pour écrire le pluriel.",
    successCriteria: [
      "Je reconnais si le nom est au singulier ou au pluriel.",
      "J'ajoute -s au nom au pluriel.",
      "Je vérifie que le déterminant est accordé.",
    ],
    lessonIds: [],
    status: "upcoming",
    sequence: {
      id: "seq-ce1-fr-orth-marquer-pluriel",
      competencyId: "ce1-fr-orth-marquer-pluriel",
      title: "Écrire le pluriel",
      status: "upcoming",
      steps: [],
    },
  },
  {
    id: "ce1-ma-num-lire-ecrire-100",
    slug: "lire-et-ecrire-les-nombres-jusqua-100",
    levelSlug: "ce1",
    subject: "Mathématiques",
    domainSlug: "mathematiques",
    subdomainSlug: "numeration",
    title: "Lire et écrire les nombres jusqu'à 100",
    observableObjective:
      "Comprendre la valeur positionnelle des dizaines et des unités.",
    successCriteria: [
      "Je lis un nombre à deux chiffres.",
      "J'écris en chiffres un nombre dit à l'oral.",
      "Je repère les dizaines et les unités.",
    ],
    lessonIds: [],
    status: "upcoming",
    sequence: {
      id: "seq-ce1-ma-num-lire-ecrire-100",
      competencyId: "ce1-ma-num-lire-ecrire-100",
      title: "Lire et écrire jusqu'à 100",
      status: "upcoming",
      steps: [],
    },
  },
  {
    id: "ce1-ma-geo-perimetre",
    slug: "mesurer-le-perimetre-dune-figure-simple",
    levelSlug: "ce1",
    subject: "Mathématiques",
    domainSlug: "mathematiques",
    subdomainSlug: "geometrie",
    title: "Mesurer le périmètre d'une figure simple",
    observableObjective:
      "Additionner les côtés d'un polygone pour calculer son périmètre.",
    successCriteria: [
      "Je mesure chaque côté de la figure.",
      "J'additionne les longueurs obtenues.",
      "J'écris le résultat avec son unité.",
    ],
    lessonIds: [],
    status: "upcoming",
    sequence: {
      id: "seq-ce1-ma-geo-perimetre",
      competencyId: "ce1-ma-geo-perimetre",
      title: "Calculer le contour",
      status: "upcoming",
      steps: [],
    },
  },
  {
    id: "ce1-ma-num-comparer-ranger-100",
    slug: "comparer-et-ranger-des-nombres-jusqua-100",
    levelSlug: "ce1",
    subject: "Mathématiques",
    domainSlug: "mathematiques",
    subdomainSlug: "numeration",
    title: "Comparer et ranger des nombres jusqu'à 100",
    observableObjective:
      "Ordonner une liste de nombres à deux chiffres en utilisant < et >.",
    successCriteria: [
      "Je compare les dizaines d'abord.",
      "Je compare les unités si les dizaines sont égales.",
      "Je classe les nombres dans le bon ordre.",
    ],
    lessonIds: [],
    status: "upcoming",
    sequence: {
      id: "seq-ce1-ma-num-comparer-ranger-100",
      competencyId: "ce1-ma-num-comparer-ranger-100",
      title: "Comparer et ordonner",
      status: "upcoming",
      steps: [],
    },
  },
  {
    id: "ce1-ma-cal-tables-addition",
    slug: "memoriser-les-tables-daddition",
    levelSlug: "ce1",
    subject: "Mathématiques",
    domainSlug: "mathematiques",
    subdomainSlug: "calcul",
    title: "Mémoriser les tables d'addition",
    observableObjective:
      "Restituer de mémoire les résultats des additions jusqu'à 10 + 10.",
    successCriteria: [
      "Je donne le résultat sans calcul pour les sommes simples.",
      "Je reconnais les compléments à 10.",
      "Je vérifie un résultat incertain avec une stratégie connue.",
    ],
    lessonIds: [],
    status: "upcoming",
    sequence: {
      id: "seq-ce1-ma-cal-tables-addition",
      competencyId: "ce1-ma-cal-tables-addition",
      title: "Restituer et vérifier",
      status: "upcoming",
      steps: [],
    },
  },
] as const satisfies LearningCompetency[];
