import type { LearningCompetency } from "@/content/learning-architecture-types";

export const ce2Competencies = [
  {
    id: "ce2-ma-cm-ajouter-9-19-29",
    slug: "ajouter-9-19-29-rapidement",
    levelSlug: "ce2",
    subject: "Mathématiques",
    domainSlug: "mathematiques",
    subdomainSlug: "calcul-mental",
    title: "Ajouter 9, 19 ou 29 rapidement",
    observableObjective:
      "Transformer un ajout proche d'une dizaine en calcul mental plus simple.",
    successCriteria: [
      "Je reconnais +9, +19 ou +29.",
      "J'ajoute la dizaine ronde.",
      "Je retire 1 et je vérifie le résultat.",
    ],
    lessonIds: ["ce2-ma-cm-ajouter9"],
    guideCharacter: {
      characterSlug: "esteban",
      name: "Esteban",
    },
    status: "in-progress",
    sequence: {
      id: "seq-ce2-ma-cm-ajouter-9-19-29",
      competencyId: "ce2-ma-cm-ajouter-9-19-29",
      title: "Construire la stratégie de calcul",
      status: "in-progress",
      steps: [
        {
          id: "seq-ce2-ma-cm-ajouter-9-19-29-1",
          order: 1,
          kind: "discovery",
          title: "Observer la stratégie",
          objective: "Comprendre pourquoi +9 peut devenir +10 puis -1.",
          status: "in-progress",
        },
        {
          id: "seq-ce2-ma-cm-ajouter-9-19-29-3",
          order: 3,
          kind: "guided-practice",
          title: "S'entraîner avec guidage",
          objective: "Appliquer la transformation sur quelques calculs.",
          status: "upcoming",
        },
        {
          id: "seq-ce2-ma-cm-ajouter-9-19-29-5",
          order: 5,
          kind: "assessment",
          title: "Calculer et expliquer",
          objective: "Donner le résultat et nommer la stratégie utilisée.",
          status: "upcoming",
        },
      ],
    },
  },
  {
    id: "ce2-fr-lc-informations-principales",
    slug: "identifier-les-informations-principales-dun-texte",
    levelSlug: "ce2",
    subject: "Français",
    domainSlug: "francais",
    subdomainSlug: "lecture-comprehension",
    title: "Identifier les informations principales d'un texte",
    observableObjective:
      "Repérer les informations essentielles d'un texte court.",
    successCriteria: [
      "Je distingue les détails et les informations importantes.",
      "Je retrouve les éléments essentiels.",
      "Je rends compte du texte en une phrase.",
    ],
    lessonIds: [],
    status: "upcoming",
    sequence: {
      id: "seq-ce2-fr-lc-informations-principales",
      competencyId: "ce2-fr-lc-informations-principales",
      title: "Repérer l'essentiel",
      status: "upcoming",
      steps: [],
    },
  },
  {
    id: "ce2-fr-ecr-court-texte-organise",
    slug: "produire-un-court-texte-organise",
    levelSlug: "ce2",
    subject: "Français",
    domainSlug: "francais",
    subdomainSlug: "ecriture",
    title: "Produire un court texte organisé",
    observableObjective:
      "Écrire trois à cinq phrases liées à une consigne.",
    successCriteria: [
      "Je respecte le sujet demandé.",
      "Mes phrases s'enchaînent clairement.",
      "Je relis pour corriger les oublis simples.",
    ],
    lessonIds: [],
    status: "upcoming",
    sequence: {
      id: "seq-ce2-fr-ecr-court-texte-organise",
      competencyId: "ce2-fr-ecr-court-texte-organise",
      title: "Organiser quelques phrases",
      status: "upcoming",
      steps: [],
    },
  },
  {
    id: "ce2-fr-edl-accords-groupe-nominal",
    slug: "accorder-dans-le-groupe-nominal",
    levelSlug: "ce2",
    subject: "Français",
    domainSlug: "francais",
    subdomainSlug: "etude-de-la-langue",
    title: "Accorder dans le groupe nominal",
    observableObjective:
      "Marquer le genre et le nombre dans un groupe nominal simple.",
    successCriteria: [
      "Je repère le nom noyau.",
      "J'accorde le déterminant.",
      "J'accorde l'adjectif quand il est présent.",
    ],
    lessonIds: [],
    status: "upcoming",
    sequence: {
      id: "seq-ce2-fr-edl-accords-groupe-nominal",
      competencyId: "ce2-fr-edl-accords-groupe-nominal",
      title: "Accorder le groupe nominal",
      status: "upcoming",
      steps: [],
    },
  },
  {
    id: "ce2-ma-num-comparer-nombres-1000",
    slug: "comparer-et-ranger-des-nombres-jusqua-1000",
    levelSlug: "ce2",
    subject: "Mathématiques",
    domainSlug: "mathematiques",
    subdomainSlug: "numeration",
    title: "Comparer et ranger des nombres jusqu'à 1 000",
    observableObjective:
      "Ordonner des nombres en utilisant centaines, dizaines et unités.",
    successCriteria: [
      "Je compare d'abord les centaines.",
      "Je poursuis avec les dizaines puis les unités.",
      "Je range les nombres dans le bon ordre.",
    ],
    lessonIds: [],
    status: "upcoming",
    sequence: {
      id: "seq-ce2-ma-num-comparer-nombres-1000",
      competencyId: "ce2-ma-num-comparer-nombres-1000",
      title: "Comparer par rangs",
      status: "upcoming",
      steps: [],
    },
  },
  {
    id: "ce2-ma-prob-multiplicatifs-simples",
    slug: "resoudre-un-probleme-multiplicatif-simple",
    levelSlug: "ce2",
    subject: "Mathématiques",
    domainSlug: "mathematiques",
    subdomainSlug: "problemes",
    title: "Résoudre un problème multiplicatif simple",
    observableObjective:
      "Utiliser addition réitérée ou multiplication dans une situation courte.",
    successCriteria: [
      "Je repère les groupes égaux.",
      "Je choisis addition réitérée ou multiplication.",
      "J'écris le résultat avec une phrase réponse.",
    ],
    lessonIds: [],
    status: "upcoming",
    sequence: {
      id: "seq-ce2-ma-prob-multiplicatifs-simples",
      competencyId: "ce2-ma-prob-multiplicatifs-simples",
      title: "Calculer des groupes égaux",
      status: "upcoming",
      steps: [],
    },
  },
  {
    id: "ce2-fr-lc-texte-documentaire-court",
    slug: "lire-un-texte-documentaire-court",
    levelSlug: "ce2",
    subject: "Français",
    domainSlug: "francais",
    subdomainSlug: "lecture-comprehension",
    title: "Lire un texte documentaire court",
    observableObjective:
      "Repérer la structure et les informations-clés d'un texte informatif.",
    successCriteria: [
      "Je repère le thème du texte.",
      "Je retrouve les informations importantes.",
      "J'utilise les titres ou indices de mise en page.",
    ],
    lessonIds: [],
    status: "upcoming",
    sequence: {
      id: "seq-ce2-fr-lc-texte-documentaire-court",
      competencyId: "ce2-fr-lc-texte-documentaire-court",
      title: "Lire pour s'informer",
      status: "upcoming",
      steps: [],
    },
  },
  {
    id: "ce2-ma-gm-longueurs-simples",
    slug: "mesurer-et-convertir-des-longueurs-simples",
    levelSlug: "ce2",
    subject: "Mathématiques",
    domainSlug: "mathematiques",
    subdomainSlug: "grandeurs-mesures",
    title: "Mesurer et convertir des longueurs simples",
    observableObjective:
      "Utiliser m, dm, cm et mm dans des conversions voisines.",
    successCriteria: [
      "Je choisis une unité adaptée.",
      "Je mesure avec soin.",
      "Je convertis entre deux unités voisines.",
    ],
    lessonIds: [],
    status: "upcoming",
    sequence: {
      id: "seq-ce2-ma-gm-longueurs-simples",
      competencyId: "ce2-ma-gm-longueurs-simples",
      title: "Mesurer et convertir",
      status: "upcoming",
      steps: [],
    },
  },
  {
    id: "ce2-ma-geo-tracer-figure-simple",
    slug: "tracer-une-figure-simple",
    levelSlug: "ce2",
    subject: "Mathématiques",
    domainSlug: "mathematiques",
    subdomainSlug: "geometrie",
    title: "Tracer une figure simple",
    observableObjective:
      "Utiliser règle et équerre pour reproduire une figure guidée.",
    successCriteria: [
      "Je repère les mesures utiles.",
      "J'utilise l'outil adapté.",
      "Je vérifie la forme obtenue.",
    ],
    lessonIds: [],
    status: "upcoming",
    sequence: {
      id: "seq-ce2-ma-geo-tracer-figure-simple",
      competencyId: "ce2-ma-geo-tracer-figure-simple",
      title: "Tracer avec les outils",
      status: "upcoming",
      steps: [],
    },
  },
  {
    id: "ce2-qdm-espace-lire-plan-simple",
    slug: "lire-un-plan-simple",
    levelSlug: "ce2",
    subject: "Questionner le monde",
    domainSlug: "questionner-le-monde",
    subdomainSlug: "espace-temps",
    title: "Lire un plan simple",
    observableObjective:
      "Orienter un plan et repérer un lieu avec une légende simple.",
    successCriteria: [
      "Je repère la légende.",
      "J'oriente le plan.",
      "Je localise le lieu demandé.",
    ],
    lessonIds: [],
    status: "upcoming",
    sequence: {
      id: "seq-ce2-qdm-espace-lire-plan-simple",
      competencyId: "ce2-qdm-espace-lire-plan-simple",
      title: "Se repérer sur un plan",
      status: "upcoming",
      steps: [],
    },
  },
  {
    id: "ce2-qdm-temps-frise-chronologique",
    slug: "situer-un-evenement-sur-une-frise-chronologique",
    levelSlug: "ce2",
    subject: "Questionner le monde",
    domainSlug: "questionner-le-monde",
    subdomainSlug: "espace-temps",
    title: "Situer un événement sur une frise chronologique",
    observableObjective:
      "Placer et relier des événements simples sur une frise.",
    successCriteria: [
      "Je lis le sens de la frise.",
      "Je place l'événement au bon endroit.",
      "Je compare avant, après et pendant.",
    ],
    lessonIds: [],
    status: "upcoming",
    sequence: {
      id: "seq-ce2-qdm-temps-frise-chronologique",
      competencyId: "ce2-qdm-temps-frise-chronologique",
      title: "Placer dans le temps",
      status: "upcoming",
      steps: [],
    },
  },
  {
    id: "ce2-ma-num-lire-ecrire-1000",
    slug: "lire-et-ecrire-les-nombres-jusqua-1000",
    levelSlug: "ce2",
    subject: "Mathématiques",
    domainSlug: "mathematiques",
    subdomainSlug: "numeration",
    title: "Lire et écrire les nombres jusqu'à 1 000",
    observableObjective:
      "Comprendre la valeur positionnelle des centaines, dizaines et unités.",
    successCriteria: [
      "Je lis un nombre à trois chiffres.",
      "J'écris en chiffres un nombre dit à l'oral.",
      "Je repère les centaines, les dizaines et les unités.",
    ],
    lessonIds: [],
    status: "upcoming",
    sequence: {
      id: "seq-ce2-ma-num-lire-ecrire-1000",
      competencyId: "ce2-ma-num-lire-ecrire-1000",
      title: "Lire et écrire jusqu'à 1 000",
      status: "upcoming",
      steps: [],
    },
  },
  {
    id: "ce2-ma-gm-masses",
    slug: "comparer-et-mesurer-des-masses",
    levelSlug: "ce2",
    subject: "Mathématiques",
    domainSlug: "mathematiques",
    subdomainSlug: "grandeurs-mesures",
    title: "Comparer et mesurer des masses",
    observableObjective:
      "Utiliser kg et g pour peser et comparer des objets.",
    successCriteria: [
      "Je lis la graduation d'une balance.",
      "Je choisis l'unité adaptée (kg ou g).",
      "Je compare deux masses et j'explique laquelle est plus lourde.",
    ],
    lessonIds: [],
    status: "upcoming",
    sequence: {
      id: "seq-ce2-ma-gm-masses",
      competencyId: "ce2-ma-gm-masses",
      title: "Peser et comparer",
      status: "upcoming",
      steps: [],
    },
  },
  {
    id: "ce2-fr-lc-reformuler",
    slug: "reformuler-ce-quon-a-compris",
    levelSlug: "ce2",
    subject: "Français",
    domainSlug: "francais",
    subdomainSlug: "lecture-comprehension",
    title: "Reformuler ce qu'on a compris",
    observableObjective:
      "Résumer un passage d'un texte avec ses propres mots.",
    successCriteria: [
      "Je n'utilise pas les mêmes mots que le texte.",
      "Je conserve l'idée principale du passage.",
      "Ma reformulation est compréhensible par quelqu'un qui n'a pas lu le texte.",
    ],
    lessonIds: [],
    status: "upcoming",
    sequence: {
      id: "seq-ce2-fr-lc-reformuler",
      competencyId: "ce2-fr-lc-reformuler",
      title: "Dire avec ses mots",
      status: "upcoming",
      steps: [],
    },
  },
  {
    id: "ce2-ma-cm-tables-multiplication",
    slug: "memoriser-les-tables-de-multiplication-2-a-5",
    levelSlug: "ce2",
    subject: "Mathématiques",
    domainSlug: "mathematiques",
    subdomainSlug: "calcul-mental",
    title: "Mémoriser les tables de multiplication (2 à 5)",
    observableObjective:
      "Restituer de mémoire les produits des tables de 2 à 5.",
    successCriteria: [
      "Je donne le résultat sans calcul pour les tables de 2 et 5.",
      "Je retrouve rapidement les résultats des tables de 3 et 4.",
      "Je vérifie un résultat incertain par addition réitérée.",
    ],
    lessonIds: [],
    status: "upcoming",
    sequence: {
      id: "seq-ce2-ma-cm-tables-multiplication",
      competencyId: "ce2-ma-cm-tables-multiplication",
      title: "Mémoriser et restituer",
      status: "upcoming",
      steps: [],
    },
  },
  {
    id: "ce2-fr-oral-presenter-info",
    slug: "presenter-une-information-a-loral",
    levelSlug: "ce2",
    subject: "Français",
    domainSlug: "francais",
    subdomainSlug: "oral",
    title: "Présenter une information à l'oral",
    observableObjective:
      "Exposer brièvement une information avec un vocabulaire précis.",
    successCriteria: [
      "J'annonce clairement mon sujet.",
      "J'utilise un vocabulaire adapté.",
      "Je parle assez fort et clairement pour être compris.",
    ],
    lessonIds: [],
    status: "upcoming",
    sequence: {
      id: "seq-ce2-fr-oral-presenter-info",
      competencyId: "ce2-fr-oral-presenter-info",
      title: "Prendre la parole et informer",
      status: "upcoming",
      steps: [],
    },
  },
  {
    id: "ce2-fr-ecr-reviser-texte",
    slug: "reviser-son-texte-avec-une-aide",
    levelSlug: "ce2",
    subject: "Français",
    domainSlug: "francais",
    subdomainSlug: "ecriture",
    title: "Réviser son texte avec une aide",
    observableObjective:
      "Identifier et corriger une erreur dans son propre texte à l'aide d'une liste de vérification.",
    successCriteria: [
      "Je relis mon texte phrase par phrase.",
      "Je repère une erreur signalée dans la liste de vérification.",
      "Je la corrige et je vérifie la correction.",
    ],
    lessonIds: [],
    status: "upcoming",
    sequence: {
      id: "seq-ce2-fr-ecr-reviser-texte",
      competencyId: "ce2-fr-ecr-reviser-texte",
      title: "Relire et corriger",
      status: "upcoming",
      steps: [],
    },
  },
  {
    id: "ce2-fr-lc-faits-opinions",
    slug: "distinguer-faits-et-opinions-dans-un-texte",
    levelSlug: "ce2",
    subject: "Français",
    domainSlug: "francais",
    subdomainSlug: "lecture-comprehension",
    title: "Distinguer faits et opinions dans un texte",
    observableObjective:
      "Identifier dans un texte court ce qui est affirmé ou supposé.",
    successCriteria: [
      "Je repère une information vérifiable dans le texte.",
      "Je repère un avis ou une opinion de l'auteur.",
      "Je justifie ma distinction en citant un indice du texte.",
    ],
    lessonIds: [],
    status: "upcoming",
    sequence: {
      id: "seq-ce2-fr-lc-faits-opinions",
      competencyId: "ce2-fr-lc-faits-opinions",
      title: "Fait ou opinion ?",
      status: "upcoming",
      steps: [],
    },
  },
] as const satisfies LearningCompetency[];
