// Carte du programme CM1 — Cycle 3, primaire.
// Le site organise ; les PDF enseignent.
// Aucun contenu pédagogique complet : uniquement objectifs observables,
// critères courts et ressources PDF prévues sans href.

import type { CurriculumLevelMap } from "@/content/curriculum-map-types";
import type { ResourceSlot } from "@/content/learning-architecture-types";

const PLANNED_PDF_RESOURCES: ResourceSlot[] = [
  {
    kind: "lesson-pdf",
    label: "Leçon PDF",
    resource: { kind: "lesson-pdf", label: "Leçon PDF", status: "planned" },
  },
  {
    kind: "exercises-pdf",
    label: "Exercices PDF",
    resource: {
      kind: "exercises-pdf",
      label: "Exercices PDF",
      status: "planned",
    },
  },
  {
    kind: "correction-pdf",
    label: "Correction PDF",
    resource: {
      kind: "correction-pdf",
      label: "Correction PDF",
      status: "planned",
    },
  },
  {
    kind: "projectable-pdf",
    label: "Support projetable",
    resource: {
      kind: "projectable-pdf",
      label: "Support projetable",
      status: "planned",
    },
  },
  {
    kind: "parent-sheet-pdf",
    label: "Fiche parent",
    resource: {
      kind: "parent-sheet-pdf",
      label: "Fiche parent",
      status: "planned",
    },
  },
];

export const cm1CurriculumLevelMap: CurriculumLevelMap = {
  levelSlug: "cm1",
  domains: [
    {
      domainSlug: "francais",
      subject: "Français",
      label: "Français",
      subdomains: [
        {
          subdomainSlug: "lecture-comprehension",
          label: "Lecture et compréhension",
          entries: [
            {
              id: "cm1-fr-lc-intentions-personnage-entry",
              levelSlug: "cm1",
              subject: "Français",
              domainSlug: "francais",
              subdomainSlug: "lecture-comprehension",
              title: "Comprendre les intentions d'un personnage",
              officialReference: "Cycle 3 — Lecture et compréhension de l'écrit",
              observableObjective:
                "L'élève déduit ce qu'un personnage cherche à faire à partir de ses paroles et de ses actions.",
              successCriteria: [
                "Je relève ce que le personnage dit.",
                "Je relève ce que le personnage fait.",
                "Je formule une intention et je la justifie.",
              ],
              status: "in-progress",
              resourceSlots: PLANNED_PDF_RESOURCES,
              competencyId: "cm1-fr-lc-intentions-personnage",
            },
            {
              id: "cm1-fr-lc-inference-entry",
              levelSlug: "cm1",
              subject: "Français",
              domainSlug: "francais",
              subdomainSlug: "lecture-comprehension",
              title: "Inférer un sens implicite",
              officialReference: "Cycle 3 — Lecture et compréhension de l'écrit",
              observableObjective:
                "L'élève comprend une information non dite en s'appuyant sur des indices du texte.",
              successCriteria: [
                "Je relève un indice dans le texte.",
                "Je formule ce que le texte suggère sans le dire.",
                "Je justifie mon inférence brièvement.",
              ],
              status: "upcoming",
              resourceSlots: PLANNED_PDF_RESOURCES,
              competencyId: "cm1-fr-lc-inference-simple",
            },
            {
              id: "cm1-fr-lc-texte-documentaire-entry",
              levelSlug: "cm1",
              subject: "Français",
              domainSlug: "francais",
              subdomainSlug: "lecture-comprehension",
              title: "Lire et comprendre un texte documentaire",
              officialReference: "Cycle 3 — Lecture et compréhension de l'écrit",
              observableObjective:
                "L'élève repère l'organisation et les informations principales d'un texte informatif.",
              successCriteria: [
                "Je repère le thème général du texte.",
                "J'identifie l'organisation du texte (titres, paragraphes).",
                "Je retrouve les informations principales sans recopier le texte.",
              ],
              status: "upcoming",
              resourceSlots: PLANNED_PDF_RESOURCES,
              competencyId: "cm1-fr-lc-texte-informatif",
            },
            {
              id: "cm1-fr-lc-resumer-texte",
              levelSlug: "cm1",
              subject: "Français",
              domainSlug: "francais",
              subdomainSlug: "lecture-comprehension",
              title: "Résumer un texte lu",
              officialReference: "Cycle 3 — Lecture et compréhension de l'écrit",
              observableObjective:
                "L'élève reformule l'essentiel d'un texte en deux ou trois phrases courtes.",
              successCriteria: [
                "Je retiens les informations clés.",
                "Je reformule sans recopier.",
                "Mon résumé tient en deux ou trois phrases.",
              ],
              status: "upcoming",
              resourceSlots: PLANNED_PDF_RESOURCES,
            },
          ],
        },
        {
          subdomainSlug: "ecriture",
          label: "Écriture et production d'écrit",
          entries: [
            {
              id: "cm1-fr-ec-planifier-entry",
              levelSlug: "cm1",
              subject: "Français",
              domainSlug: "francais",
              subdomainSlug: "ecriture",
              title: "Planifier son écrit avant de rédiger",
              officialReference: "Cycle 3 — Écriture",
              observableObjective:
                "L'élève organise ses idées en liste ou en plan avant d'écrire.",
              successCriteria: [
                "Je note mes idées principales avant d'écrire.",
                "Je les ordonne dans un plan ou une liste.",
                "Je m'appuie sur ce plan pendant la rédaction.",
              ],
              status: "upcoming",
              resourceSlots: PLANNED_PDF_RESOURCES,
              competencyId: "cm1-fr-ecr-planifier",
            },
            {
              id: "cm1-fr-ec-texte-structure-entry",
              levelSlug: "cm1",
              subject: "Français",
              domainSlug: "francais",
              subdomainSlug: "ecriture",
              title: "Produire un texte structuré",
              officialReference: "Cycle 3 — Écriture",
              observableObjective:
                "L'élève écrit un texte organisé avec un début, un développement et une fin.",
              successCriteria: [
                "J'organise mes idées avant d'écrire.",
                "Je regroupe les phrases qui vont ensemble.",
                "Je relis pour améliorer la clarté.",
              ],
              status: "upcoming",
              resourceSlots: PLANNED_PDF_RESOURCES,
              competencyId: "cm1-fr-ecr-texte-structure",
            },
            {
              id: "cm1-fr-ec-relire-corriger",
              levelSlug: "cm1",
              subject: "Français",
              domainSlug: "francais",
              subdomainSlug: "ecriture",
              title: "Relire et corriger sa production",
              officialReference: "Cycle 3 — Écriture",
              observableObjective:
                "L'élève relit son texte et améliore la syntaxe, l'orthographe et la cohérence.",
              successCriteria: [
                "Je relis mon texte une fois entier.",
                "Je corrige au moins une erreur repérée.",
                "Je vérifie que mon texte se comprend bien.",
              ],
              status: "upcoming",
              resourceSlots: PLANNED_PDF_RESOURCES,
            },
          ],
        },
        {
          subdomainSlug: "etude-de-la-langue",
          label: "Grammaire",
          entries: [
            {
              id: "cm1-fr-edl-sujet-verbe-entry",
              levelSlug: "cm1",
              subject: "Français",
              domainSlug: "francais",
              subdomainSlug: "etude-de-la-langue",
              title: "Identifier sujet, verbe et accords",
              officialReference: "Cycle 3 — Étude de la langue",
              observableObjective:
                "L'élève repère le sujet et le verbe pour contrôler un accord simple.",
              successCriteria: [
                "Je repère le verbe conjugué.",
                "Je retrouve son sujet.",
                "Je vérifie l'accord sujet-verbe.",
              ],
              status: "upcoming",
              resourceSlots: PLANNED_PDF_RESOURCES,
              competencyId: "cm1-fr-edl-sujet-verbe-accord",
            },
            {
              id: "cm1-fr-gr-complement-circonstanciel",
              levelSlug: "cm1",
              subject: "Français",
              domainSlug: "francais",
              subdomainSlug: "etude-de-la-langue",
              title: "Identifier les compléments circonstanciels",
              officialReference: "Cycle 3 — Étude de la langue",
              observableObjective:
                "L'élève repère les compléments de temps, lieu et manière dans une phrase.",
              successCriteria: [
                "Je pose les questions où, quand, comment.",
                "Je repère le complément correspondant.",
                "Je supprime le complément pour vérifier qu'il est détachable.",
              ],
              status: "upcoming",
              resourceSlots: PLANNED_PDF_RESOURCES,
            },
            {
              id: "cm1-fr-gr-accord-adjectif-qualificatif",
              levelSlug: "cm1",
              subject: "Français",
              domainSlug: "francais",
              subdomainSlug: "etude-de-la-langue",
              title: "Accorder l'adjectif qualificatif",
              officialReference: "Cycle 3 — Étude de la langue",
              observableObjective:
                "L'élève accorde l'adjectif en genre et en nombre avec le nom qu'il qualifie.",
              successCriteria: [
                "Je repère le nom auquel se rapporte l'adjectif.",
                "J'accorde en genre (féminin) et en nombre (pluriel).",
                "Je vérifie les cas particuliers (-eux, -al, etc.).",
              ],
              status: "upcoming",
              resourceSlots: PLANNED_PDF_RESOURCES,
            },
          ],
        },
        {
          subdomainSlug: "conjugaison",
          label: "Conjugaison",
          entries: [
            {
              id: "cm1-fr-conj-imparfait",
              levelSlug: "cm1",
              subject: "Français",
              domainSlug: "francais",
              subdomainSlug: "conjugaison",
              title: "Conjuguer à l'imparfait de l'indicatif",
              officialReference: "Cycle 3 — Étude de la langue",
              observableObjective:
                "L'élève conjugue des verbes des 1er et 2e groupes et les verbes fréquents à l'imparfait.",
              successCriteria: [
                "Je reconnais les terminaisons de l'imparfait (-ais, -ait, -ions…).",
                "Je conjugue correctement un verbe en -er à l'imparfait.",
                "Je distingue imparfait et passé composé dans un texte.",
              ],
              status: "upcoming",
              resourceSlots: PLANNED_PDF_RESOURCES,
            },
            {
              id: "cm1-fr-conj-futur-simple",
              levelSlug: "cm1",
              subject: "Français",
              domainSlug: "francais",
              subdomainSlug: "conjugaison",
              title: "Conjuguer au futur simple",
              officialReference: "Cycle 3 — Étude de la langue",
              observableObjective:
                "L'élève conjugue des verbes fréquents au futur simple de l'indicatif.",
              successCriteria: [
                "Je reconnais les terminaisons du futur (-rai, -ras, -ra…).",
                "Je conjugue correctement être, avoir, aller, faire au futur.",
                "Je distingue futur simple et présent dans une phrase.",
              ],
              status: "upcoming",
              resourceSlots: PLANNED_PDF_RESOURCES,
            },
            {
              id: "cm1-fr-conj-passe-simple-initiation",
              levelSlug: "cm1",
              subject: "Français",
              domainSlug: "francais",
              subdomainSlug: "conjugaison",
              title: "Reconnaître le passé simple dans un texte",
              officialReference: "Cycle 3 — Étude de la langue",
              observableObjective:
                "L'élève reconnaît les formes du passé simple des verbes du 1er groupe et de quelques verbes fréquents.",
              successCriteria: [
                "Je repère les terminaisons -a, -èrent pour les verbes en -er.",
                "Je distingue passé simple et imparfait dans un texte.",
                "Je ne confonds pas il chanta (passé simple) et il chantait (imparfait).",
              ],
              status: "upcoming",
              resourceSlots: PLANNED_PDF_RESOURCES,
            },
          ],
        },
        {
          subdomainSlug: "orthographe",
          label: "Orthographe",
          entries: [
            {
              id: "cm1-fr-orth-homophones-a-à",
              levelSlug: "cm1",
              subject: "Français",
              domainSlug: "francais",
              subdomainSlug: "orthographe",
              title: "Distinguer a / à et les homophones courants",
              officialReference: "Cycle 3 — Étude de la langue",
              observableObjective:
                "L'élève choisit la graphie correcte pour les homophones a/à, et/est, on/ont, son/sont.",
              successCriteria: [
                "Je remplace a par avait pour vérifier.",
                "Je distingue et (conjonction) de est (verbe être).",
                "Je reconnais on/ont et son/sont dans une phrase.",
              ],
              status: "upcoming",
              resourceSlots: PLANNED_PDF_RESOURCES,
            },
            {
              id: "cm1-fr-orth-accord-sujet-verbe-texte",
              levelSlug: "cm1",
              subject: "Français",
              domainSlug: "francais",
              subdomainSlug: "orthographe",
              title: "Orthographier l'accord sujet-verbe dans un texte",
              officialReference: "Cycle 3 — Étude de la langue",
              observableObjective:
                "L'élève contrôle et corrige l'accord sujet-verbe dans un texte court.",
              successCriteria: [
                "Je repère le sujet avant d'écrire le verbe.",
                "Je contrôle la terminaison du verbe en relecture.",
                "Je corrige les erreurs d'accord détectées.",
              ],
              status: "upcoming",
              resourceSlots: PLANNED_PDF_RESOURCES,
            },
            {
              id: "cm1-fr-orth-pluriel-noms-adjectifs",
              levelSlug: "cm1",
              subject: "Français",
              domainSlug: "francais",
              subdomainSlug: "orthographe",
              title: "Former le pluriel des noms et des adjectifs",
              officialReference: "Cycle 3 — Étude de la langue",
              observableObjective:
                "L'élève forme le pluriel des noms et adjectifs courants, y compris les cas particuliers fréquents.",
              successCriteria: [
                "Je forme le pluriel régulier en -s.",
                "Je connais les pluriels en -aux (cheval → chevaux).",
                "Je reconnais les noms invariables au pluriel.",
              ],
              status: "upcoming",
              resourceSlots: PLANNED_PDF_RESOURCES,
            },
          ],
        },
        {
          subdomainSlug: "lexique",
          label: "Lexique",
          entries: [
            {
              id: "cm1-fr-lex-synonymes-antonymes",
              levelSlug: "cm1",
              subject: "Français",
              domainSlug: "francais",
              subdomainSlug: "lexique",
              title: "Utiliser synonymes et antonymes",
              officialReference: "Cycle 3 — Étude de la langue",
              observableObjective:
                "L'élève choisit un synonyme ou un antonyme adapté au contexte d'une phrase.",
              successCriteria: [
                "Je remplace un mot par un synonyme sans changer le sens.",
                "Je trouve l'antonyme d'un adjectif courant.",
                "Je vérifie que le mot choisi convient dans la phrase.",
              ],
              status: "upcoming",
              resourceSlots: PLANNED_PDF_RESOURCES,
            },
            {
              id: "cm1-fr-lex-familles-de-mots",
              levelSlug: "cm1",
              subject: "Français",
              domainSlug: "francais",
              subdomainSlug: "lexique",
              title: "Reconnaître et utiliser des familles de mots",
              officialReference: "Cycle 3 — Étude de la langue",
              observableObjective:
                "L'élève identifie le radical d'un mot et regroupe des mots de la même famille.",
              successCriteria: [
                "Je repère le radical commun à plusieurs mots.",
                "Je forme des mots de la même famille avec des préfixes ou suffixes.",
                "Je m'appuie sur la famille de mots pour orthographier.",
              ],
              status: "upcoming",
              resourceSlots: PLANNED_PDF_RESOURCES,
            },
            {
              id: "cm1-fr-lex-sens-contexte",
              levelSlug: "cm1",
              subject: "Français",
              domainSlug: "francais",
              subdomainSlug: "lexique",
              title: "Comprendre le sens d'un mot selon le contexte",
              officialReference: "Cycle 3 — Étude de la langue",
              observableObjective:
                "L'élève choisit le sens adapté d'un mot polysémique à partir du contexte de la phrase.",
              successCriteria: [
                "Je repère les indices du contexte autour du mot.",
                "Je distingue les différents sens possibles.",
                "Je justifie le sens retenu par le contexte.",
              ],
              status: "upcoming",
              resourceSlots: PLANNED_PDF_RESOURCES,
            },
          ],
        },
        {
          subdomainSlug: "langage-oral",
          label: "Langage oral",
          entries: [
            {
              id: "cm1-fr-or-avis-argumente-entry",
              levelSlug: "cm1",
              subject: "Français",
              domainSlug: "francais",
              subdomainSlug: "langage-oral",
              title: "Présenter un avis argumenté",
              officialReference: "Cycle 3 — Comprendre et s'exprimer à l'oral",
              observableObjective:
                "L'élève donne un avis court et l'appuie sur un exemple ou un indice.",
              successCriteria: [
                "J'annonce clairement mon avis.",
                "Je donne au moins un argument.",
                "Je m'appuie sur un exemple précis.",
              ],
              status: "upcoming",
              resourceSlots: PLANNED_PDF_RESOURCES,
              competencyId: "cm1-fr-oral-avis-argumente",
            },
            {
              id: "cm1-fr-or-exposer-sujet",
              levelSlug: "cm1",
              subject: "Français",
              domainSlug: "francais",
              subdomainSlug: "langage-oral",
              title: "Exposer un sujet de façon organisée",
              officialReference: "Cycle 3 — Comprendre et s'exprimer à l'oral",
              observableObjective:
                "L'élève présente un exposé court en suivant un plan en deux ou trois parties.",
              successCriteria: [
                "J'annonce le plan de mon exposé.",
                "Je parle en phrases complètes.",
                "Je conclue par une phrase de synthèse.",
              ],
              status: "upcoming",
              resourceSlots: PLANNED_PDF_RESOURCES,
            },
          ],
        },
      ],
    },
    {
      domainSlug: "mathematiques",
      subject: "Mathématiques",
      label: "Mathématiques",
      subdomains: [
        {
          subdomainSlug: "numeration",
          label: "Numération — grands nombres et fractions",
          entries: [
            {
              id: "cm1-ma-num-fractions-entry",
              levelSlug: "cm1",
              subject: "Mathématiques",
              domainSlug: "mathematiques",
              subdomainSlug: "numeration",
              title: "Comprendre la notion de fraction",
              officialReference: "Cycle 3 — Nombres et calculs",
              observableObjective:
                "L'élève partage en parties égales et lit ou écrit une fraction simple.",
              successCriteria: [
                "Je reconnais que les parties doivent être égales.",
                "Je lis une fraction (numérateur et dénominateur).",
                "Je représente une fraction simple sur un dessin ou une droite graduée.",
              ],
              status: "upcoming",
              resourceSlots: PLANNED_PDF_RESOURCES,
              competencyId: "cm1-ma-num-fractions",
            },
            {
              id: "cm1-ma-num-grands-nombres-entry",
              levelSlug: "cm1",
              subject: "Mathématiques",
              domainSlug: "mathematiques",
              subdomainSlug: "numeration",
              title: "Lire, écrire et comparer les grands nombres",
              officialReference: "Cycle 3 — Nombres et calculs",
              observableObjective:
                "L'élève lit, écrit et compare des nombres jusqu'au million.",
              successCriteria: [
                "Je repère les classes d'un nombre.",
                "J'écris un nombre dicté en chiffres.",
                "Je compare deux nombres et je justifie.",
              ],
              status: "upcoming",
              resourceSlots: PLANNED_PDF_RESOURCES,
              competencyId: "cm1-ma-num-grands-nombres",
            },
            {
              id: "cm1-ma-num-comparer-fractions",
              levelSlug: "cm1",
              subject: "Mathématiques",
              domainSlug: "mathematiques",
              subdomainSlug: "numeration",
              title: "Comparer et ordonner des fractions simples",
              officialReference: "Cycle 3 — Nombres et calculs",
              observableObjective:
                "L'élève compare des fractions de même dénominateur ou des fractions à l'unité.",
              successCriteria: [
                "Je compare deux fractions de même dénominateur.",
                "Je repère les fractions supérieures ou inférieures à 1.",
                "Je place des fractions simples sur une droite graduée.",
              ],
              status: "upcoming",
              resourceSlots: PLANNED_PDF_RESOURCES,
            },
          ],
        },
        {
          subdomainSlug: "calcul-pose",
          label: "Calcul posé",
          entries: [
            {
              id: "cm1-ma-cal-multiplication-entry",
              levelSlug: "cm1",
              subject: "Mathématiques",
              domainSlug: "mathematiques",
              subdomainSlug: "calcul-pose",
              title: "Poser et calculer une multiplication",
              officialReference: "Cycle 3 — Nombres et calculs",
              observableObjective:
                "L'élève calcule le produit de deux entiers par l'algorithme de la multiplication.",
              successCriteria: [
                "Je pose la multiplication en colonnes.",
                "Je multiplie chiffre par chiffre en gérant les retenues.",
                "Je vérifie le résultat par une estimation.",
              ],
              status: "upcoming",
              resourceSlots: PLANNED_PDF_RESOURCES,
              competencyId: "cm1-ma-cal-multiplication",
            },
            {
              id: "cm1-ma-cal-division-entry",
              levelSlug: "cm1",
              subject: "Mathématiques",
              domainSlug: "mathematiques",
              subdomainSlug: "calcul-pose",
              title: "Poser et calculer une division euclidienne",
              officialReference: "Cycle 3 — Nombres et calculs",
              observableObjective:
                "L'élève calcule le quotient et le reste d'une division posée.",
              successCriteria: [
                "Je pose la division avec les bons nombres.",
                "Je calcule quotient et reste étape par étape.",
                "Je vérifie que le reste est inférieur au diviseur.",
              ],
              status: "upcoming",
              resourceSlots: PLANNED_PDF_RESOURCES,
              competencyId: "cm1-ma-cal-division",
            },
          ],
        },
        {
          subdomainSlug: "calcul-mental",
          label: "Calcul mental",
          entries: [
            {
              id: "cm1-ma-cm-tables-multiplication",
              levelSlug: "cm1",
              subject: "Mathématiques",
              domainSlug: "mathematiques",
              subdomainSlug: "calcul-mental",
              title: "Automatiser les tables de multiplication",
              officialReference: "Cycle 3 — Nombres et calculs",
              observableObjective:
                "L'élève restitue rapidement et sans erreur les résultats des tables de 2 à 9.",
              successCriteria: [
                "Je donne le résultat d'une multiplication simple sans hésitation.",
                "J'utilise les tables pour calculer des produits plus complexes.",
                "Je calcule rapidement des multiples de 10, 100, 1000.",
              ],
              status: "upcoming",
              resourceSlots: PLANNED_PDF_RESOURCES,
            },
            {
              id: "cm1-ma-cm-strategies-calcul",
              levelSlug: "cm1",
              subject: "Mathématiques",
              domainSlug: "mathematiques",
              subdomainSlug: "calcul-mental",
              title: "Utiliser des stratégies de calcul mental",
              officialReference: "Cycle 3 — Nombres et calculs",
              observableObjective:
                "L'élève choisit une décomposition utile pour calculer mentalement et l'explique.",
              successCriteria: [
                "Je décompose un calcul pour le simplifier.",
                "Je justifie ma stratégie en une phrase.",
                "Je vérifie la vraisemblance du résultat.",
              ],
              status: "upcoming",
              resourceSlots: PLANNED_PDF_RESOURCES,
            },
          ],
        },
        {
          subdomainSlug: "problemes",
          label: "Résolution de problèmes",
          entries: [
            {
              id: "cm1-ma-prob-etapes-entry",
              levelSlug: "cm1",
              subject: "Mathématiques",
              domainSlug: "mathematiques",
              subdomainSlug: "problemes",
              title: "Résoudre un problème à étapes",
              officialReference: "Cycle 3 — Résolution de problèmes",
              observableObjective:
                "L'élève organise deux calculs successifs pour répondre à une question.",
              successCriteria: [
                "Je repère les données utiles.",
                "Je choisis l'ordre des calculs.",
                "Je justifie ma démarche par une phrase courte.",
              ],
              status: "upcoming",
              resourceSlots: PLANNED_PDF_RESOURCES,
              competencyId: "cm1-ma-prob-etapes",
            },
            {
              id: "cm1-ma-prob-proportionnalite-simple",
              levelSlug: "cm1",
              subject: "Mathématiques",
              domainSlug: "mathematiques",
              subdomainSlug: "problemes",
              title: "Résoudre un problème de proportionnalité simple",
              officialReference: "Cycle 3 — Résolution de problèmes",
              observableObjective:
                "L'élève reconnaît une situation de proportionnalité et applique la règle de trois.",
              successCriteria: [
                "Je repère que le rapport entre les grandeurs est constant.",
                "J'organise les données dans un tableau.",
                "Je calcule la valeur manquante.",
              ],
              status: "upcoming",
              resourceSlots: PLANNED_PDF_RESOURCES,
            },
          ],
        },
        {
          subdomainSlug: "grandeurs-mesures",
          label: "Grandeurs et mesures",
          entries: [
            {
              id: "cm1-ma-gm-aires-perimetres-entry",
              levelSlug: "cm1",
              subject: "Mathématiques",
              domainSlug: "mathematiques",
              subdomainSlug: "grandeurs-mesures",
              title: "Distinguer aire et périmètre",
              officialReference: "Cycle 3 — Grandeurs et mesures",
              observableObjective:
                "L'élève choisit la grandeur adaptée selon la question posée.",
              successCriteria: [
                "Je reconnais si l'on cherche un contour ou une surface.",
                "Je choisis l'unité adaptée.",
                "J'explique mon choix en une phrase.",
              ],
              status: "upcoming",
              resourceSlots: PLANNED_PDF_RESOURCES,
              competencyId: "cm1-ma-gm-aires-perimetres",
            },
            {
              id: "cm1-ma-gm-conversions-unites",
              levelSlug: "cm1",
              subject: "Mathématiques",
              domainSlug: "mathematiques",
              subdomainSlug: "grandeurs-mesures",
              title: "Convertir des unités de mesure",
              officialReference: "Cycle 3 — Grandeurs et mesures",
              observableObjective:
                "L'élève convertit des mesures de longueur, masse et contenance en utilisant les équivalences.",
              successCriteria: [
                "Je connais les équivalences entre km, m, cm et mm.",
                "Je convertis des unités de masse (kg, g).",
                "J'utilise un tableau de conversion si nécessaire.",
              ],
              status: "upcoming",
              resourceSlots: PLANNED_PDF_RESOURCES,
            },
            {
              id: "cm1-ma-gm-durees-calcul",
              levelSlug: "cm1",
              subject: "Mathématiques",
              domainSlug: "mathematiques",
              subdomainSlug: "grandeurs-mesures",
              title: "Calculer des durées",
              officialReference: "Cycle 3 — Grandeurs et mesures",
              observableObjective:
                "L'élève calcule une durée ou une heure d'arrivée à partir d'une heure de départ.",
              successCriteria: [
                "Je repère heure de départ et heure d'arrivée.",
                "Je calcule la durée par addition ou soustraction.",
                "Je convertis des heures en minutes si nécessaire.",
              ],
              status: "upcoming",
              resourceSlots: PLANNED_PDF_RESOURCES,
            },
          ],
        },
        {
          subdomainSlug: "geometrie",
          label: "Géométrie",
          entries: [
            {
              id: "cm1-ma-geo-figures-entry",
              levelSlug: "cm1",
              subject: "Mathématiques",
              domainSlug: "mathematiques",
              subdomainSlug: "geometrie",
              title: "Décrire et construire des figures",
              officialReference: "Cycle 3 — Espace et géométrie",
              observableObjective:
                "L'élève utilise les propriétés de figures pour décrire ou tracer.",
              successCriteria: [
                "Je nomme les propriétés utiles.",
                "J'utilise les outils adaptés.",
                "Je vérifie la figure construite.",
              ],
              status: "upcoming",
              resourceSlots: PLANNED_PDF_RESOURCES,
              competencyId: "cm1-ma-geo-decrire-construire-figures",
            },
            {
              id: "cm1-ma-geo-symetrie-axiale",
              levelSlug: "cm1",
              subject: "Mathématiques",
              domainSlug: "mathematiques",
              subdomainSlug: "geometrie",
              title: "Reconnaître et tracer une symétrie axiale",
              officialReference: "Cycle 3 — Espace et géométrie",
              observableObjective:
                "L'élève reconnaît qu'une figure est symétrique et trace le symétrique d'un point.",
              successCriteria: [
                "Je vérifie qu'une figure est symétrique par pliage ou mesure.",
                "Je trace l'axe de symétrie d'une figure.",
                "Je construis le symétrique d'un point par rapport à un axe.",
              ],
              status: "upcoming",
              resourceSlots: PLANNED_PDF_RESOURCES,
            },
            {
              id: "cm1-ma-geo-angles",
              levelSlug: "cm1",
              subject: "Mathématiques",
              domainSlug: "mathematiques",
              subdomainSlug: "geometrie",
              title: "Comparer et mesurer des angles",
              officialReference: "Cycle 3 — Espace et géométrie",
              observableObjective:
                "L'élève compare des angles en utilisant l'équerre et mesure un angle au rapporteur.",
              successCriteria: [
                "Je distingue angle aigu, droit et obtus.",
                "J'utilise l'équerre pour vérifier un angle droit.",
                "Je mesure un angle simple au rapporteur.",
              ],
              status: "upcoming",
              resourceSlots: PLANNED_PDF_RESOURCES,
            },
          ],
        },
      ],
    },
    {
      domainSlug: "histoire-geographie",
      subject: "Histoire-Géographie",
      label: "Histoire-Géographie",
      subdomains: [
        {
          subdomainSlug: "reperes-chronologiques",
          label: "Repères chronologiques",
          entries: [
            {
              id: "cm1-hg-rc-lire-frise-chronologique",
              levelSlug: "cm1",
              subject: "Histoire-Géographie",
              domainSlug: "histoire-geographie",
              subdomainSlug: "reperes-chronologiques",
              title: "Lire et compléter une frise chronologique",
              officialReference: "Cycle 3 — Histoire",
              observableObjective:
                "L'élève place des événements sur une frise et utilise le vocabulaire des grandes périodes.",
              successCriteria: [
                "Je distingue avant et après J.-C.",
                "Je place des événements clés sur la frise.",
                "Je nomme les grandes périodes historiques.",
              ],
              status: "upcoming",
              resourceSlots: PLANNED_PDF_RESOURCES,
            },
          ],
        },
        {
          subdomainSlug: "antiquite",
          label: "Antiquité",
          entries: [
            {
              id: "cm1-hi-ant-situer-civilisation-entry",
              levelSlug: "cm1",
              subject: "Histoire-Géographie",
              domainSlug: "histoire-geographie",
              subdomainSlug: "antiquite",
              title: "Situer une civilisation dans le temps",
              officialReference: "Cycle 3 — Histoire",
              observableObjective:
                "L'élève place une civilisation antique sur une frise.",
              successCriteria: [
                "Je repère la période donnée.",
                "Je place la civilisation sur la frise.",
                "Je compare avec une autre période.",
              ],
              status: "upcoming",
              resourceSlots: PLANNED_PDF_RESOURCES,
              competencyId: "cm1-hi-ant-situer-civilisation",
            },
            {
              id: "cm1-hg-ant-rome-gaule",
              levelSlug: "cm1",
              subject: "Histoire-Géographie",
              domainSlug: "histoire-geographie",
              subdomainSlug: "antiquite",
              title: "Décrire la romanisation de la Gaule",
              officialReference: "Cycle 3 — Histoire",
              observableObjective:
                "L'élève décrit deux ou trois transformations apportées par Rome en Gaule.",
              successCriteria: [
                "Je cite un vestige architectural romain.",
                "Je relève une transformation de la vie quotidienne.",
                "Je situe la conquête romaine sur la frise.",
              ],
              status: "upcoming",
              resourceSlots: PLANNED_PDF_RESOURCES,
            },
          ],
        },
        {
          subdomainSlug: "moyen-age",
          label: "Moyen Âge",
          entries: [
            {
              id: "cm1-hg-ma-seigneurie-feodalite",
              levelSlug: "cm1",
              subject: "Histoire-Géographie",
              domainSlug: "histoire-geographie",
              subdomainSlug: "moyen-age",
              title: "Comprendre la société féodale",
              officialReference: "Cycle 3 — Histoire",
              observableObjective:
                "L'élève décrit la hiérarchie féodale et les relations entre seigneur et paysan.",
              successCriteria: [
                "Je cite les trois ordres de la société médiévale.",
                "Je décris le château fort et sa fonction.",
                "J'explique le lien de vassalité simplement.",
              ],
              status: "upcoming",
              resourceSlots: PLANNED_PDF_RESOURCES,
            },
            {
              id: "cm1-hg-ma-cathédrale-foi",
              levelSlug: "cm1",
              subject: "Histoire-Géographie",
              domainSlug: "histoire-geographie",
              subdomainSlug: "moyen-age",
              title: "Décrire la place de l'Église au Moyen Âge",
              officialReference: "Cycle 3 — Histoire",
              observableObjective:
                "L'élève explique le rôle central de l'Église dans la vie médiévale.",
              successCriteria: [
                "Je décris la cathédrale comme lieu de vie communautaire.",
                "Je nomme un rôle social de l'Église (soins, instruction).",
                "Je situe la construction des cathédrales dans le temps.",
              ],
              status: "upcoming",
              resourceSlots: PLANNED_PDF_RESOURCES,
            },
          ],
        },
        {
          subdomainSlug: "temps-modernes",
          label: "Temps modernes",
          entries: [
            {
              id: "cm1-hg-tm-renaissance-humanisme",
              levelSlug: "cm1",
              subject: "Histoire-Géographie",
              domainSlug: "histoire-geographie",
              subdomainSlug: "temps-modernes",
              title: "Repérer les changements de la Renaissance",
              officialReference: "Cycle 3 — Histoire",
              observableObjective:
                "L'élève décrit deux ou trois transformations culturelles ou scientifiques de la Renaissance.",
              successCriteria: [
                "Je cite une découverte ou invention de la période.",
                "Je place la Renaissance sur la frise.",
                "Je donne un exemple d'humanisme (arts, sciences, exploration).",
              ],
              status: "upcoming",
              resourceSlots: PLANNED_PDF_RESOURCES,
            },
          ],
        },
        {
          subdomainSlug: "geographie",
          label: "Géographie",
          entries: [
            {
              id: "cm1-geo-decrire-territoire-entry",
              levelSlug: "cm1",
              subject: "Histoire-Géographie",
              domainSlug: "histoire-geographie",
              subdomainSlug: "geographie",
              title: "Décrire un espace de vie ou un territoire",
              officialReference: "Cycle 3 — Géographie",
              observableObjective:
                "L'élève présente les caractéristiques d'un espace à partir d'une carte.",
              successCriteria: [
                "Je repère le type de document.",
                "Je relève deux informations utiles.",
                "Je décris le territoire avec un vocabulaire précis.",
              ],
              status: "upcoming",
              resourceSlots: PLANNED_PDF_RESOURCES,
              competencyId: "cm1-geo-decrire-territoire",
            },
            {
              id: "cm1-geo-lire-paysage-entry",
              levelSlug: "cm1",
              subject: "Histoire-Géographie",
              domainSlug: "histoire-geographie",
              subdomainSlug: "geographie",
              title: "Lire un paysage et identifier ses composantes",
              officialReference: "Cycle 3 — Géographie",
              observableObjective:
                "L'élève distingue les éléments naturels et humains d'un paysage.",
              successCriteria: [
                "Je repère les éléments naturels.",
                "Je repère les éléments humains.",
                "Je décris le paysage avec le vocabulaire adapté.",
              ],
              status: "upcoming",
              resourceSlots: PLANNED_PDF_RESOURCES,
              competencyId: "cm1-geo-lire-paysage",
            },
            {
              id: "cm1-geo-commune-rural-urbain",
              levelSlug: "cm1",
              subject: "Histoire-Géographie",
              domainSlug: "histoire-geographie",
              subdomainSlug: "geographie",
              title: "Distinguer commune rurale et commune urbaine",
              officialReference: "Cycle 3 — Géographie",
              observableObjective:
                "L'élève compare une commune rurale et une commune urbaine à partir de documents.",
              successCriteria: [
                "Je relève des différences de population et d'activités.",
                "Je décris les fonctions d'une commune (mairie, école, services).",
                "Je situe ma commune sur une carte.",
              ],
              status: "upcoming",
              resourceSlots: PLANNED_PDF_RESOURCES,
            },
          ],
        },
      ],
    },
    {
      domainSlug: "sciences",
      subject: "Sciences et technologie",
      label: "Sciences et technologie",
      subdomains: [
        {
          subdomainSlug: "vivant",
          label: "Le vivant",
          entries: [
            {
              id: "cm1-sc-vivant-besoins-entry",
              levelSlug: "cm1",
              subject: "Sciences et technologie",
              domainSlug: "sciences",
              subdomainSlug: "vivant",
              title: "Décrire les besoins du vivant",
              officialReference: "Cycle 3 — Sciences et technologie",
              observableObjective:
                "L'élève identifie des besoins communs et des différences entre êtres vivants.",
              successCriteria: [
                "Je relève une observation utile.",
                "Je nomme un besoin du vivant.",
                "Je compare deux êtres vivants simplement.",
              ],
              status: "upcoming",
              resourceSlots: PLANNED_PDF_RESOURCES,
              competencyId: "cm1-sc-vivant-besoins",
            },
            {
              id: "cm1-sc-vivant-chaines-alimentaires",
              levelSlug: "cm1",
              subject: "Sciences et technologie",
              domainSlug: "sciences",
              subdomainSlug: "vivant",
              title: "Construire une chaîne alimentaire",
              officialReference: "Cycle 3 — Sciences et technologie",
              observableObjective:
                "L'élève ordonne producteur, consommateur et décomposeur dans une chaîne alimentaire.",
              successCriteria: [
                "Je repère le producteur de la chaîne.",
                "Je place les maillons dans l'ordre.",
                "Je justifie par qui mange qui.",
              ],
              status: "upcoming",
              resourceSlots: PLANNED_PDF_RESOURCES,
            },
            {
              id: "cm1-sc-vivant-reproduction-animaux",
              levelSlug: "cm1",
              subject: "Sciences et technologie",
              domainSlug: "sciences",
              subdomainSlug: "vivant",
              title: "Décrire la reproduction chez les animaux",
              officialReference: "Cycle 3 — Sciences et technologie",
              observableObjective:
                "L'élève distingue reproduction ovipare et vivipare et donne un exemple de chaque.",
              successCriteria: [
                "Je distingue ovipare et vivipare.",
                "Je donne un exemple d'animal de chaque type.",
                "Je décris une étape du développement.",
              ],
              status: "upcoming",
              resourceSlots: PLANNED_PDF_RESOURCES,
            },
          ],
        },
        {
          subdomainSlug: "matiere",
          label: "La matière",
          entries: [
            {
              id: "cm1-sc-mat-etats-eau",
              levelSlug: "cm1",
              subject: "Sciences et technologie",
              domainSlug: "sciences",
              subdomainSlug: "matiere",
              title: "Décrire les états et changements de l'eau",
              officialReference: "Cycle 3 — Sciences et technologie",
              observableObjective:
                "L'élève nomme les trois états de l'eau et associe chaque changement à une température.",
              successCriteria: [
                "Je nomme les trois états de l'eau.",
                "Je cite la température de fusion et d'ébullition.",
                "Je décris un changement d'état simple.",
              ],
              status: "upcoming",
              resourceSlots: PLANNED_PDF_RESOURCES,
            },
            {
              id: "cm1-sc-mat-melanges-solutions",
              levelSlug: "cm1",
              subject: "Sciences et technologie",
              domainSlug: "sciences",
              subdomainSlug: "matiere",
              title: "Distinguer mélange et dissolution",
              officialReference: "Cycle 3 — Sciences et technologie",
              observableObjective:
                "L'élève distingue un mélange homogène d'un mélange hétérogène et réalise une dissolution.",
              successCriteria: [
                "Je distingue mélange homogène et hétérogène.",
                "Je décris une dissolution (sel dans l'eau).",
                "Je propose une façon de séparer un mélange.",
              ],
              status: "upcoming",
              resourceSlots: PLANNED_PDF_RESOURCES,
            },
          ],
        },
        {
          subdomainSlug: "energie",
          label: "Énergie et technologie",
          entries: [
            {
              id: "cm1-sc-en-circuit-electrique",
              levelSlug: "cm1",
              subject: "Sciences et technologie",
              domainSlug: "sciences",
              subdomainSlug: "energie",
              title: "Réaliser et schématiser un circuit électrique",
              officialReference: "Cycle 3 — Sciences et technologie",
              observableObjective:
                "L'élève monte un circuit simple et le représente par un schéma conventionnel.",
              successCriteria: [
                "Je réalise un circuit qui allume une lampe.",
                "Je distingue circuit ouvert et circuit fermé.",
                "Je représente le circuit par un schéma simple.",
              ],
              status: "upcoming",
              resourceSlots: PLANNED_PDF_RESOURCES,
            },
            {
              id: "cm1-sc-en-sources-energie",
              levelSlug: "cm1",
              subject: "Sciences et technologie",
              domainSlug: "sciences",
              subdomainSlug: "energie",
              title: "Identifier des sources d'énergie",
              officialReference: "Cycle 3 — Sciences et technologie",
              observableObjective:
                "L'élève distingue sources d'énergie renouvelables et non renouvelables.",
              successCriteria: [
                "Je cite deux sources d'énergie renouvelables.",
                "Je cite deux sources non renouvelables.",
                "J'explique pourquoi économiser l'énergie est utile.",
              ],
              status: "upcoming",
              resourceSlots: PLANNED_PDF_RESOURCES,
            },
            {
              id: "cm1-sc-en-objet-technique",
              levelSlug: "cm1",
              subject: "Sciences et technologie",
              domainSlug: "sciences",
              subdomainSlug: "energie",
              title: "Décrire la fonction d'un objet technique",
              officialReference: "Cycle 3 — Sciences et technologie",
              observableObjective:
                "L'élève identifie la fonction principale d'un objet technique et décrit ses composants.",
              successCriteria: [
                "Je nomme la fonction principale de l'objet.",
                "J'identifie les pièces principales.",
                "Je relie chaque pièce à son rôle.",
              ],
              status: "upcoming",
              resourceSlots: PLANNED_PDF_RESOURCES,
            },
          ],
        },
        {
          subdomainSlug: "environnement",
          label: "Environnement et développement durable",
          entries: [
            {
              id: "cm1-sc-env-impact-activites-humaines",
              levelSlug: "cm1",
              subject: "Sciences et technologie",
              domainSlug: "sciences",
              subdomainSlug: "environnement",
              title: "Identifier l'impact des activités humaines sur l'environnement",
              officialReference: "Cycle 3 — Sciences et technologie",
              observableObjective:
                "L'élève décrit deux effets des activités humaines sur un milieu naturel proche.",
              successCriteria: [
                "Je repère un impact positif ou négatif.",
                "Je donne un exemple concret.",
                "Je propose une action pour limiter un impact négatif.",
              ],
              status: "upcoming",
              resourceSlots: PLANNED_PDF_RESOURCES,
            },
          ],
        },
      ],
    },
    {
      domainSlug: "emc",
      subject: "EMC",
      label: "EMC",
      subdomains: [
        {
          subdomainSlug: "regles-droits-responsabilites",
          label: "Règles, droits et responsabilités",
          entries: [
            {
              id: "cm1-emc-rdr-respecter-regles-loi",
              levelSlug: "cm1",
              subject: "EMC",
              domainSlug: "emc",
              subdomainSlug: "regles-droits-responsabilites",
              title: "Comprendre la nécessité de la règle et de la loi",
              officialReference: "Cycle 3 — EMC",
              observableObjective:
                "L'élève explique pourquoi des règles communes sont nécessaires dans une société.",
              successCriteria: [
                "Je distingue règle de classe et loi.",
                "Je cite une conséquence concrète du non-respect d'une règle.",
                "J'explique ce que protège une règle ou une loi.",
              ],
              status: "upcoming",
              resourceSlots: PLANNED_PDF_RESOURCES,
            },
            {
              id: "cm1-emc-rdr-droits-devoirs",
              levelSlug: "cm1",
              subject: "EMC",
              domainSlug: "emc",
              subdomainSlug: "regles-droits-responsabilites",
              title: "Distinguer droits et devoirs du citoyen",
              officialReference: "Cycle 3 — EMC",
              observableObjective:
                "L'élève associe un droit fondamental à un devoir correspondant.",
              successCriteria: [
                "Je cite un droit de l'enfant.",
                "Je cite un devoir qui lui correspond.",
                "Je comprends que droits et devoirs vont ensemble.",
              ],
              status: "upcoming",
              resourceSlots: PLANNED_PDF_RESOURCES,
            },
          ],
        },
        {
          subdomainSlug: "valeurs-republique",
          label: "Valeurs et symboles de la République",
          entries: [
            {
              id: "cm1-emc-vr-devise-symboles",
              levelSlug: "cm1",
              subject: "EMC",
              domainSlug: "emc",
              subdomainSlug: "valeurs-republique",
              title: "Connaître les symboles de la République française",
              officialReference: "Cycle 3 — EMC",
              observableObjective:
                "L'élève nomme et explique la signification des principaux symboles républicains.",
              successCriteria: [
                "Je cite les trois mots de la devise.",
                "J'explique ce que représente chaque terme.",
                "Je nomme deux autres symboles de la République.",
              ],
              status: "upcoming",
              resourceSlots: PLANNED_PDF_RESOURCES,
            },
            {
              id: "cm1-emc-vr-egalite-discriminations",
              levelSlug: "cm1",
              subject: "EMC",
              domainSlug: "emc",
              subdomainSlug: "valeurs-republique",
              title: "Comprendre le principe d'égalité et rejeter les discriminations",
              officialReference: "Cycle 3 — EMC",
              observableObjective:
                "L'élève reconnaît une situation de discrimination et propose une réaction respectueuse.",
              successCriteria: [
                "Je définis ce qu'est une discrimination.",
                "Je donne un exemple de discrimination.",
                "Je propose une réponse respectueuse de la valeur d'égalité.",
              ],
              status: "upcoming",
              resourceSlots: PLANNED_PDF_RESOURCES,
            },
          ],
        },
        {
          subdomainSlug: "jugement-esprit-critique",
          label: "Jugement et esprit critique",
          entries: [
            {
              id: "cm1-emc-jec-verifier-information",
              levelSlug: "cm1",
              subject: "EMC",
              domainSlug: "emc",
              subdomainSlug: "jugement-esprit-critique",
              title: "Vérifier une information avant de la partager",
              officialReference: "Cycle 3 — EMC",
              observableObjective:
                "L'élève identifie une source et propose une vérification avant de partager une information.",
              successCriteria: [
                "Je repère qui a produit l'information.",
                "Je propose une façon de la vérifier.",
                "Je distingue information et rumeur.",
              ],
              status: "upcoming",
              resourceSlots: PLANNED_PDF_RESOURCES,
            },
            {
              id: "cm1-emc-jec-debat-regle",
              levelSlug: "cm1",
              subject: "EMC",
              domainSlug: "emc",
              subdomainSlug: "jugement-esprit-critique",
              title: "Participer à un débat argumenté",
              officialReference: "Cycle 3 — EMC",
              observableObjective:
                "L'élève prend la parole pour défendre un point de vue en s'appuyant sur un argument.",
              successCriteria: [
                "J'attends mon tour de parole.",
                "Je formule un argument clairement.",
                "J'écoute et peux reformuler l'avis adverse.",
              ],
              status: "upcoming",
              resourceSlots: PLANNED_PDF_RESOURCES,
            },
          ],
        },
      ],
    },
    {
      domainSlug: "eps",
      subject: "EPS",
      label: "EPS",
      subdomains: [
        {
          subdomainSlug: "performance-mesure",
          label: "Produire et mesurer une performance",
          entries: [
            {
              id: "cm1-eps-pm-courir-durer",
              levelSlug: "cm1",
              subject: "EPS",
              domainSlug: "eps",
              subdomainSlug: "performance-mesure",
              title: "Courir en gérant son effort dans la durée",
              officialReference: "Cycle 3 — EPS",
              observableObjective:
                "L'élève court à une allure régulière et maintient son effort jusqu'à la fin.",
              successCriteria: [
                "Je choisis une allure que je peux tenir.",
                "Je contrôle ma respiration.",
                "Je compare mes performances sur plusieurs séances.",
              ],
              status: "upcoming",
              resourceSlots: PLANNED_PDF_RESOURCES,
            },
            {
              id: "cm1-eps-pm-lancer-distance",
              levelSlug: "cm1",
              subject: "EPS",
              domainSlug: "eps",
              subdomainSlug: "performance-mesure",
              title: "Lancer en visant la distance",
              officialReference: "Cycle 3 — EPS",
              observableObjective:
                "L'élève améliore sa technique de lancer et mesure sa performance.",
              successCriteria: [
                "J'adopte une posture de lancer adaptée.",
                "Je mesure la distance atteinte.",
                "Je cherche à progresser entre les essais.",
              ],
              status: "upcoming",
              resourceSlots: PLANNED_PDF_RESOURCES,
            },
          ],
        },
        {
          subdomainSlug: "jeux-sports-collectifs",
          label: "Jeux et sports collectifs",
          entries: [
            {
              id: "cm1-eps-jsc-cooperer-strategier",
              levelSlug: "cm1",
              subject: "EPS",
              domainSlug: "eps",
              subdomainSlug: "jeux-sports-collectifs",
              title: "Coopérer et élaborer une stratégie collective",
              officialReference: "Cycle 3 — EPS",
              observableObjective:
                "L'élève propose une stratégie simple pour son équipe et la respecte en jeu.",
              successCriteria: [
                "J'identifie un espace libre à exploiter.",
                "Je communique une intention à mes partenaires.",
                "Je respecte le projet collectif de l'équipe.",
              ],
              status: "upcoming",
              resourceSlots: PLANNED_PDF_RESOURCES,
            },
            {
              id: "cm1-eps-jsc-respecter-regles-fairplay",
              levelSlug: "cm1",
              subject: "EPS",
              domainSlug: "eps",
              subdomainSlug: "jeux-sports-collectifs",
              title: "Respecter les règles et adopter un comportement fair-play",
              officialReference: "Cycle 3 — EPS",
              observableObjective:
                "L'élève accepte la décision de l'arbitre et reconnaît la victoire ou la défaite avec fairness.",
              successCriteria: [
                "Je respecte les règles du jeu.",
                "J'accepte la décision de l'arbitre.",
                "Je félicite l'adversaire après la rencontre.",
              ],
              status: "upcoming",
              resourceSlots: PLANNED_PDF_RESOURCES,
            },
          ],
        },
        {
          subdomainSlug: "activites-artistiques",
          label: "Activités gymniques et artistiques",
          entries: [
            {
              id: "cm1-eps-aa-composer-sequence",
              levelSlug: "cm1",
              subject: "EPS",
              domainSlug: "eps",
              subdomainSlug: "activites-artistiques",
              title: "Composer et présenter une séquence gymnique",
              officialReference: "Cycle 3 — EPS",
              observableObjective:
                "L'élève compose une séquence de trois éléments enchaînés et la présente devant un groupe.",
              successCriteria: [
                "Je choisis trois éléments variés.",
                "Je les enchaîne sans m'arrêter.",
                "Je présente ma séquence avec un début et une fin clairs.",
              ],
              status: "upcoming",
              resourceSlots: PLANNED_PDF_RESOURCES,
            },
          ],
        },
        {
          subdomainSlug: "plein-air-orientation",
          label: "Plein air et orientation",
          entries: [
            {
              id: "cm1-eps-oa-sorienter-carte",
              levelSlug: "cm1",
              subject: "EPS",
              domainSlug: "eps",
              subdomainSlug: "plein-air-orientation",
              title: "S'orienter avec une carte dans un espace inconnu",
              officialReference: "Cycle 3 — EPS",
              observableObjective:
                "L'élève utilise une carte et des balises pour se déplacer dans un espace extérieur.",
              successCriteria: [
                "J'oriente la carte par rapport à l'environnement.",
                "Je choisis un trajet pour trouver les balises.",
                "Je note les balises trouvées dans l'ordre.",
              ],
              status: "upcoming",
              resourceSlots: PLANNED_PDF_RESOURCES,
            },
          ],
        },
      ],
    },
    {
      domainSlug: "enseignements-artistiques",
      subject: "Enseignements artistiques",
      label: "Enseignements artistiques",
      subdomains: [
        {
          subdomainSlug: "arts-plastiques",
          label: "Arts plastiques",
          entries: [
            {
              id: "cm1-art-ap-intention-composition",
              levelSlug: "cm1",
              subject: "Enseignements artistiques",
              domainSlug: "enseignements-artistiques",
              subdomainSlug: "arts-plastiques",
              title: "Composer une image avec une intention",
              officialReference: "Cycle 3 — Enseignements artistiques",
              observableObjective:
                "L'élève organise formes, couleurs et espaces pour exprimer une idée ou une émotion.",
              successCriteria: [
                "Je définis une intention avant de produire.",
                "Je fais des choix plastiques pour l'exprimer.",
                "Je peux expliquer mes choix à l'oral.",
              ],
              status: "upcoming",
              resourceSlots: PLANNED_PDF_RESOURCES,
            },
            {
              id: "cm1-art-ap-analyser-oeuvre",
              levelSlug: "cm1",
              subject: "Enseignements artistiques",
              domainSlug: "enseignements-artistiques",
              subdomainSlug: "arts-plastiques",
              title: "Analyser une œuvre d'art avec un vocabulaire adapté",
              officialReference: "Cycle 3 — Enseignements artistiques",
              observableObjective:
                "L'élève décrit et interprète une œuvre en utilisant des termes plastiques précis.",
              successCriteria: [
                "Je décris les éléments visuels (formes, couleurs, lignes).",
                "Je distingue description et interprétation.",
                "J'utilise au moins deux termes du vocabulaire plastique.",
              ],
              status: "upcoming",
              resourceSlots: PLANNED_PDF_RESOURCES,
            },
            {
              id: "cm1-art-ap-volume-espace",
              levelSlug: "cm1",
              subject: "Enseignements artistiques",
              domainSlug: "enseignements-artistiques",
              subdomainSlug: "arts-plastiques",
              title: "Explorer la notion de volume et d'espace",
              officialReference: "Cycle 3 — Enseignements artistiques",
              observableObjective:
                "L'élève réalise une production en volume en explorant la matière et l'espace.",
              successCriteria: [
                "Je travaille en trois dimensions.",
                "J'expérimente au moins deux matériaux.",
                "Je décris l'espace occupé par ma production.",
              ],
              status: "upcoming",
              resourceSlots: PLANNED_PDF_RESOURCES,
            },
          ],
        },
        {
          subdomainSlug: "education-musicale",
          label: "Éducation musicale",
          entries: [
            {
              id: "cm1-art-mus-chanter-justesse",
              levelSlug: "cm1",
              subject: "Enseignements artistiques",
              domainSlug: "enseignements-artistiques",
              subdomainSlug: "education-musicale",
              title: "Chanter avec justesse dans un groupe",
              officialReference: "Cycle 3 — Enseignements artistiques",
              observableObjective:
                "L'élève chante avec le groupe en respectant la hauteur des notes et le tempo.",
              successCriteria: [
                "Je chante en respectant la hauteur des notes.",
                "Je reste dans le tempo collectif.",
                "J'adapte mon volume pour équilibrer le groupe.",
              ],
              status: "upcoming",
              resourceSlots: PLANNED_PDF_RESOURCES,
            },
            {
              id: "cm1-art-mus-ecoute-active",
              levelSlug: "cm1",
              subject: "Enseignements artistiques",
              domainSlug: "enseignements-artistiques",
              subdomainSlug: "education-musicale",
              title: "Écouter une œuvre et en dégager les caractéristiques",
              officialReference: "Cycle 3 — Enseignements artistiques",
              observableObjective:
                "L'élève décrit une œuvre musicale en identifiant tempo, nuances et timbre.",
              successCriteria: [
                "Je repère le tempo (rapide ou lent).",
                "Je décris les nuances (fort, doux).",
                "Je reconnais un instrument entendu.",
              ],
              status: "upcoming",
              resourceSlots: PLANNED_PDF_RESOURCES,
            },
            {
              id: "cm1-art-mus-improvisation-rythmique",
              levelSlug: "cm1",
              subject: "Enseignements artistiques",
              domainSlug: "enseignements-artistiques",
              subdomainSlug: "education-musicale",
              title: "Improviser une phrase rythmique",
              officialReference: "Cycle 3 — Enseignements artistiques",
              observableObjective:
                "L'élève crée et mémorise une courte cellule rythmique originale.",
              successCriteria: [
                "Je produis un rythme différent du modèle.",
                "Je le mémorise et le reproduis.",
                "Je l'intègre dans un enchaînement collectif.",
              ],
              status: "upcoming",
              resourceSlots: PLANNED_PDF_RESOURCES,
            },
          ],
        },
      ],
    },
    {
      domainSlug: "anglais",
      subject: "Anglais",
      label: "Anglais",
      subdomains: [
        {
          subdomainSlug: "comprendre-oral",
          label: "Comprendre à l'oral",
          entries: [
            {
              id: "cm1-ang-co-comprendre-consignes",
              levelSlug: "cm1",
              subject: "Anglais",
              domainSlug: "anglais",
              subdomainSlug: "comprendre-oral",
              title: "Comprendre des consignes et des échanges simples",
              officialReference: "Cycle 3 — Langues vivantes",
              observableObjective:
                "L'élève comprend des consignes courantes et des échanges simples prononcés clairement.",
              successCriteria: [
                "Je comprends les consignes de classe en anglais.",
                "Je repère les mots clés d'un échange court.",
                "Je peux répondre oui ou non à une question simple.",
              ],
              status: "upcoming",
              resourceSlots: PLANNED_PDF_RESOURCES,
            },
            {
              id: "cm1-ang-co-comprendre-texte-court",
              levelSlug: "cm1",
              subject: "Anglais",
              domainSlug: "anglais",
              subdomainSlug: "comprendre-oral",
              title: "Comprendre un texte oral court",
              officialReference: "Cycle 3 — Langues vivantes",
              observableObjective:
                "L'élève repère les informations principales d'un court enregistrement ou d'une histoire lue.",
              successCriteria: [
                "Je repère les personnages et le lieu.",
                "Je comprends l'action principale.",
                "Je réponds à une question de compréhension simple.",
              ],
              status: "upcoming",
              resourceSlots: PLANNED_PDF_RESOURCES,
            },
          ],
        },
        {
          subdomainSlug: "s-exprimer-oral",
          label: "S'exprimer à l'oral",
          entries: [
            {
              id: "cm1-ang-so-se-presenter",
              levelSlug: "cm1",
              subject: "Anglais",
              domainSlug: "anglais",
              subdomainSlug: "s-exprimer-oral",
              title: "Se présenter en anglais",
              officialReference: "Cycle 3 — Langues vivantes",
              observableObjective:
                "L'élève donne son prénom, son âge et ses goûts en phrases courtes.",
              successCriteria: [
                "Je dis mon prénom et mon âge correctement.",
                "J'exprime un goût avec I like / I don't like.",
                "Je prononce les mots appris de façon compréhensible.",
              ],
              status: "upcoming",
              resourceSlots: PLANNED_PDF_RESOURCES,
            },
            {
              id: "cm1-ang-so-decrire-image",
              levelSlug: "cm1",
              subject: "Anglais",
              domainSlug: "anglais",
              subdomainSlug: "s-exprimer-oral",
              title: "Décrire une image en anglais",
              officialReference: "Cycle 3 — Langues vivantes",
              observableObjective:
                "L'élève décrit une image simple en nommant personnes, objets et actions.",
              successCriteria: [
                "Je nomme ce que je vois avec le vocabulaire appris.",
                "J'utilise There is / There are.",
                "Je décris une action avec le présent en -ing.",
              ],
              status: "upcoming",
              resourceSlots: PLANNED_PDF_RESOURCES,
            },
          ],
        },
        {
          subdomainSlug: "lire-ecrire",
          label: "Lire et écrire en anglais",
          entries: [
            {
              id: "cm1-ang-le-lire-texte-court",
              levelSlug: "cm1",
              subject: "Anglais",
              domainSlug: "anglais",
              subdomainSlug: "lire-ecrire",
              title: "Lire et comprendre un texte court en anglais",
              officialReference: "Cycle 3 — Langues vivantes",
              observableObjective:
                "L'élève lit un texte simple de quelques lignes et répond à des questions de compréhension.",
              successCriteria: [
                "Je repère les mots connus.",
                "Je comprends l'idée principale du texte.",
                "Je réponds à une question de compréhension en anglais.",
              ],
              status: "upcoming",
              resourceSlots: PLANNED_PDF_RESOURCES,
            },
            {
              id: "cm1-ang-le-ecrire-phrases-simples",
              levelSlug: "cm1",
              subject: "Anglais",
              domainSlug: "anglais",
              subdomainSlug: "lire-ecrire",
              title: "Écrire des phrases simples en anglais",
              officialReference: "Cycle 3 — Langues vivantes",
              observableObjective:
                "L'élève écrit de courtes phrases correctes sur lui-même ou sur un sujet connu.",
              successCriteria: [
                "Je commence mes phrases par une majuscule.",
                "Je mets un point à la fin.",
                "J'écris deux phrases correctes avec le vocabulaire appris.",
              ],
              status: "upcoming",
              resourceSlots: PLANNED_PDF_RESOURCES,
            },
          ],
        },
      ],
    },
  ],
};
