import type { LearningCompetency } from "@/content/learning-architecture-types";

export const cm2Competencies = [
  {
    id: "cm2-fr-edl-passe-simple",
    slug: "passe-simple-formes-et-emploi",
    levelSlug: "cm2",
    subject: "Français",
    domainSlug: "francais",
    subdomainSlug: "etude-de-la-langue",
    title: "Passé simple — formes et emploi",
    observableObjective:
      "Reconnaître et conjuguer les verbes des trois groupes au passé simple dans un contexte narratif.",
    successCriteria: [
      "Je reconnais le passé simple dans un texte narratif.",
      "Je conjugue un verbe du 1er groupe au passé simple.",
      "Je conjugue un verbe du 3e groupe courant (être, avoir, venir) au passé simple.",
    ],
    lessonIds: [],
    status: "upcoming",
    sequence: {
      id: "seq-cm2-fr-edl-passe-simple",
      competencyId: "cm2-fr-edl-passe-simple",
      title: "Conjuguer au passé simple",
      status: "upcoming",
      steps: [
        {
          id: "step-cm2-fr-edl-passe-simple-1",
          order: 1,
          kind: "discovery",
          title: "Découvrir le passé simple",
          objective: "Observer des formes du passé simple dans un texte narratif et identifier les terminaisons caractéristiques.",
          status: "upcoming",
        },
        {
          id: "step-cm2-fr-edl-passe-simple-2",
          order: 2,
          kind: "explicit-lesson",
          title: "Mémoriser les terminaisons",
          objective: "Retenir les terminaisons du 1er, 2e et 3e groupe au passé simple et conjuguer des verbes modèles.",
          status: "upcoming",
        },
        {
          id: "step-cm2-fr-edl-passe-simple-3",
          order: 3,
          kind: "guided-practice",
          title: "S'entraîner à conjuguer",
          objective: "Conjuguer des verbes variés au passé simple avec appui, puis de façon autonome.",
          status: "upcoming",
        },
        {
          id: "step-cm2-fr-edl-passe-simple-4",
          order: 4,
          kind: "assessment",
          title: "Évaluer sa maîtrise",
          objective: "Reconnaître et produire des formes au passé simple dans un court texte narratif.",
          status: "upcoming",
        },
      ],
    },
  },
  {
    id: "cm2-fr-edl-accord-participe",
    slug: "accord-du-participe-passe-etre-avoir",
    levelSlug: "cm2",
    subject: "Français",
    domainSlug: "francais",
    subdomainSlug: "etude-de-la-langue",
    title: "Accord du participe passé avec être et avoir",
    observableObjective:
      "Appliquer la règle d'accord du participe passé avec les auxiliaires être et avoir (cas de base).",
    successCriteria: [
      "Je distingue les auxiliaires être et avoir.",
      "J'accorde le participe passé avec le sujet quand l'auxiliaire est être.",
      "Je n'accorde pas le participe passé avec avoir (cas de base, sans COD antéposé).",
    ],
    lessonIds: [],
    status: "upcoming",
    sequence: {
      id: "seq-cm2-fr-edl-accord-participe",
      competencyId: "cm2-fr-edl-accord-participe",
      title: "Être ou avoir : accorder le participe",
      status: "upcoming",
      steps: [
        {
          id: "step-cm2-fr-edl-accord-participe-1",
          order: 1,
          kind: "discovery",
          title: "Observer les accords dans des phrases",
          objective: "Comparer des phrases avec être et avoir pour percevoir les différences d'accord du participe passé.",
          status: "upcoming",
        },
        {
          id: "step-cm2-fr-edl-accord-participe-2",
          order: 2,
          kind: "explicit-lesson",
          title: "Comprendre la règle de base",
          objective: "Formuler la règle : accord avec le sujet avec être, pas d'accord avec avoir (cas de base).",
          status: "upcoming",
        },
        {
          id: "step-cm2-fr-edl-accord-participe-3",
          order: 3,
          kind: "guided-practice",
          title: "S'entraîner à accorder",
          objective: "Appliquer la règle sur des exercices progressifs avec et sans aide.",
          status: "upcoming",
        },
        {
          id: "step-cm2-fr-edl-accord-participe-4",
          order: 4,
          kind: "assessment",
          title: "Évaluer sa maîtrise",
          objective: "Accorder correctement le participe passé dans des phrases variées avec être et avoir.",
          status: "upcoming",
        },
      ],
    },
  },
  {
    id: "cm2-fr-edl-nature-fonction",
    slug: "nature-et-fonction-gn-cod-coi",
    levelSlug: "cm2",
    subject: "Français",
    domainSlug: "francais",
    subdomainSlug: "etude-de-la-langue",
    title: "Nature et fonction : GN, COD, COI",
    observableObjective:
      "Identifier la nature (groupe nominal) et la fonction (COD ou COI) d'un groupe dans la phrase.",
    successCriteria: [
      "Je repère un groupe nominal dans une phrase.",
      "Je distingue le COD du COI à l'aide des questions (quoi ? / à qui ?).",
      "Je justifie la fonction en posant la question appropriée.",
    ],
    lessonIds: [],
    status: "upcoming",
    sequence: {
      id: "seq-cm2-fr-edl-nature-fonction",
      competencyId: "cm2-fr-edl-nature-fonction",
      title: "Nommer et fonctionner",
      status: "upcoming",
      steps: [
        {
          id: "step-cm2-fr-edl-nature-fonction-1",
          order: 1,
          kind: "discovery",
          title: "Distinguer nature et fonction",
          objective: "Observer des groupes nominaux en phrase pour percevoir la différence entre ce qu'un mot est et ce qu'il fait.",
          status: "upcoming",
        },
        {
          id: "step-cm2-fr-edl-nature-fonction-2",
          order: 2,
          kind: "explicit-lesson",
          title: "Identifier COD et COI",
          objective: "Poser les bonnes questions (quoi ? / à qui ?) pour identifier la fonction d'un GN dans la phrase.",
          status: "upcoming",
        },
        {
          id: "step-cm2-fr-edl-nature-fonction-3",
          order: 3,
          kind: "guided-practice",
          title: "S'entraîner à analyser des GN",
          objective: "Repérer et nommer la nature et la fonction de groupes nominaux dans des phrases variées.",
          status: "upcoming",
        },
        {
          id: "step-cm2-fr-edl-nature-fonction-4",
          order: 4,
          kind: "assessment",
          title: "Évaluer sa maîtrise",
          objective: "Identifier la nature et la fonction d'un GN dans un texte et justifier sa réponse.",
          status: "upcoming",
        },
      ],
    },
  },
  {
    id: "cm2-fr-lc-implicite",
    slug: "comprendre-limplicite-et-les-sous-entendus",
    levelSlug: "cm2",
    subject: "Français",
    domainSlug: "francais",
    subdomainSlug: "lecture-comprehension",
    title: "Comprendre l'implicite et les sous-entendus",
    observableObjective:
      "Interpréter ce qu'un texte laisse entendre sans le dire en s'appuyant sur des indices textuels.",
    successCriteria: [
      "Je repère une information non dite dans le texte.",
      "Je cite les indices qui me permettent de l'inférer.",
      "Je formule le sous-entendu en une phrase justifiée.",
    ],
    lessonIds: [],
    status: "upcoming",
    sequence: {
      id: "seq-cm2-fr-lc-implicite",
      competencyId: "cm2-fr-lc-implicite",
      title: "Lire entre les lignes",
      status: "upcoming",
      steps: [
        {
          id: "step-cm2-fr-lc-implicite-1",
          order: 1,
          kind: "discovery",
          title: "Percevoir ce qui n'est pas dit",
          objective: "Lire un texte court et repérer des passages où l'auteur laisse entendre quelque chose sans l'écrire.",
          status: "upcoming",
        },
        {
          id: "step-cm2-fr-lc-implicite-2",
          order: 2,
          kind: "explicit-lesson",
          title: "Inférer à partir d'indices",
          objective: "Apprendre à s'appuyer sur des mots, des détails ou le contexte pour formuler ce que le texte sous-entend.",
          status: "upcoming",
        },
        {
          id: "step-cm2-fr-lc-implicite-3",
          order: 3,
          kind: "guided-practice",
          title: "S'entraîner à justifier ses inférences",
          objective: "Formuler des inférences et les justifier avec des indices précis tirés du texte.",
          status: "upcoming",
        },
        {
          id: "step-cm2-fr-lc-implicite-4",
          order: 4,
          kind: "assessment",
          title: "Évaluer sa maîtrise",
          objective: "Identifier un implicite dans un texte inconnu et expliquer les indices qui permettent de l'inférer.",
          status: "upcoming",
        },
      ],
    },
  },
  {
    id: "cm2-fr-ec-texte-argumentatif",
    slug: "rediger-un-texte-argumentatif-court",
    levelSlug: "cm2",
    subject: "Français",
    domainSlug: "francais",
    subdomainSlug: "ecriture",
    title: "Rédiger un texte argumentatif court",
    observableObjective:
      "Défendre un point de vue à l'écrit en formulant au moins deux arguments illustrés d'exemples.",
    successCriteria: [
      "J'annonce clairement mon point de vue.",
      "Je donne au moins deux arguments distincts.",
      "J'illustre chaque argument par un exemple.",
    ],
    lessonIds: [],
    status: "upcoming",
    sequence: {
      id: "seq-cm2-fr-ec-texte-argumentatif",
      competencyId: "cm2-fr-ec-texte-argumentatif",
      title: "Convaincre par l'écrit",
      status: "upcoming",
      steps: [
        {
          id: "step-cm2-fr-ec-texte-argumentatif-1",
          order: 1,
          kind: "discovery",
          title: "Lire et analyser un texte argumentatif",
          objective: "Repérer la thèse, les arguments et les exemples dans un texte court qui défend un point de vue.",
          status: "upcoming",
        },
        {
          id: "step-cm2-fr-ec-texte-argumentatif-2",
          order: 2,
          kind: "explicit-lesson",
          title: "Comprendre la structure argumentative",
          objective: "Identifier les éléments d'un texte argumentatif : thèse, argument, exemple, conclusion.",
          status: "upcoming",
        },
        {
          id: "step-cm2-fr-ec-texte-argumentatif-3",
          order: 3,
          kind: "guided-practice",
          title: "Rédiger avec guidage",
          objective: "Produire un texte argumentatif court à partir d'un plan guidé, avec au moins deux arguments illustrés.",
          status: "upcoming",
        },
        {
          id: "step-cm2-fr-ec-texte-argumentatif-4",
          order: 4,
          kind: "assessment",
          title: "Évaluer sa production",
          objective: "Écrire un court texte argumentatif autonome et auto-évaluer sa structure.",
          status: "upcoming",
        },
      ],
    },
  },
  {
    id: "cm2-ma-num-decimaux",
    slug: "nombres-decimaux-lire-ecrire-comparer",
    levelSlug: "cm2",
    subject: "Mathématiques",
    domainSlug: "mathematiques",
    subdomainSlug: "numeration",
    title: "Nombres décimaux — lire, écrire, comparer",
    observableObjective:
      "Lire, écrire et comparer des nombres décimaux en s'appuyant sur la valeur positionnelle des chiffres.",
    successCriteria: [
      "Je lis un nombre décimal et je nomme chaque chiffre par sa position.",
      "J'écris en chiffres un nombre décimal dicté à l'oral.",
      "Je compare deux nombres décimaux et je justifie.",
    ],
    lessonIds: [],
    status: "upcoming",
    sequence: {
      id: "seq-cm2-ma-num-decimaux",
      competencyId: "cm2-ma-num-decimaux",
      title: "Lire et écrire les décimaux",
      status: "upcoming",
      steps: [
        {
          id: "step-cm2-ma-num-decimaux-1",
          order: 1,
          kind: "discovery",
          title: "Découvrir les nombres décimaux",
          objective: "Observer des nombres décimaux dans des contextes concrets (prix, mesures) et identifier la virgule.",
          status: "upcoming",
        },
        {
          id: "step-cm2-ma-num-decimaux-2",
          order: 2,
          kind: "explicit-lesson",
          title: "Comprendre la valeur positionnelle",
          objective: "Nommer chaque chiffre d'un décimal par sa position : unités, dixièmes, centièmes.",
          status: "upcoming",
        },
        {
          id: "step-cm2-ma-num-decimaux-3",
          order: 3,
          kind: "guided-practice",
          title: "Lire, écrire et comparer",
          objective: "Lire des décimaux à l'oral, les écrire sous la dictée et les comparer deux à deux.",
          status: "upcoming",
        },
        {
          id: "step-cm2-ma-num-decimaux-4",
          order: 4,
          kind: "assessment",
          title: "Évaluer sa maîtrise",
          objective: "Lire, écrire et ordonner des décimaux dans une situation variée.",
          status: "upcoming",
        },
      ],
    },
  },
  {
    id: "cm2-ma-num-fractions-decimaux",
    slug: "fractions-et-decimaux-equivalences",
    levelSlug: "cm2",
    subject: "Mathématiques",
    domainSlug: "mathematiques",
    subdomainSlug: "numeration",
    title: "Fractions et décimaux — équivalences",
    observableObjective:
      "Passer d'une fraction simple à l'écriture décimale et inversement.",
    successCriteria: [
      "Je convertis une fraction à dénominateur 10 ou 100 en décimal.",
      "J'écris un décimal simple sous forme de fraction.",
      "Je place une fraction ou un décimal sur une droite graduée.",
    ],
    lessonIds: [],
    status: "upcoming",
    sequence: {
      id: "seq-cm2-ma-num-fractions-decimaux",
      competencyId: "cm2-ma-num-fractions-decimaux",
      title: "Passer d'une écriture à l'autre",
      status: "upcoming",
      steps: [
        {
          id: "step-cm2-ma-num-fractions-decimaux-1",
          order: 1,
          kind: "discovery",
          title: "Explorer fractions et décimaux",
          objective: "Observer sur une droite graduée la correspondance entre fractions simples et décimaux.",
          status: "upcoming",
        },
        {
          id: "step-cm2-ma-num-fractions-decimaux-2",
          order: 2,
          kind: "explicit-lesson",
          title: "Comprendre les équivalences",
          objective: "Établir les équivalences entre fractions à dénominateur 10 ou 100 et leur écriture décimale.",
          status: "upcoming",
        },
        {
          id: "step-cm2-ma-num-fractions-decimaux-3",
          order: 3,
          kind: "guided-practice",
          title: "Convertir dans les deux sens",
          objective: "Passer d'une fraction à un décimal et inversement dans des exercices variés.",
          status: "upcoming",
        },
        {
          id: "step-cm2-ma-num-fractions-decimaux-4",
          order: 4,
          kind: "assessment",
          title: "Évaluer sa maîtrise",
          objective: "Convertir des fractions en décimaux, placer des nombres sur une droite et justifier les équivalences.",
          status: "upcoming",
        },
      ],
    },
  },
  {
    id: "cm2-ma-cal-operations-decimaux",
    slug: "operations-sur-les-decimaux",
    levelSlug: "cm2",
    subject: "Mathématiques",
    domainSlug: "mathematiques",
    subdomainSlug: "calcul-pose",
    title: "Opérations sur les décimaux",
    observableObjective:
      "Poser et calculer des additions, soustractions et multiplications impliquant des nombres décimaux.",
    successCriteria: [
      "J'aligne les virgules lors de la pose de l'opération.",
      "Je calcule une addition ou soustraction de décimaux posée.",
      "Je pose et calcule une multiplication par un entier avec un résultat décimal.",
    ],
    lessonIds: [],
    status: "upcoming",
    sequence: {
      id: "seq-cm2-ma-cal-operations-decimaux",
      competencyId: "cm2-ma-cal-operations-decimaux",
      title: "Calculer avec les décimaux",
      status: "upcoming",
      steps: [
        {
          id: "step-cm2-ma-cal-operations-decimaux-1",
          order: 1,
          kind: "discovery",
          title: "Observer la pose des opérations",
          objective: "Comparer des opérations posées avec des entiers et avec des décimaux pour percevoir le rôle de la virgule.",
          status: "upcoming",
        },
        {
          id: "step-cm2-ma-cal-operations-decimaux-2",
          order: 2,
          kind: "explicit-lesson",
          title: "Comprendre l'alignement des virgules",
          objective: "Retenir que la virgule doit être alignée dans l'addition et la soustraction de décimaux.",
          status: "upcoming",
        },
        {
          id: "step-cm2-ma-cal-operations-decimaux-3",
          order: 3,
          kind: "guided-practice",
          title: "Poser et calculer",
          objective: "Poser et effectuer des additions, soustractions et multiplications sur des décimaux avec vérification.",
          status: "upcoming",
        },
        {
          id: "step-cm2-ma-cal-operations-decimaux-4",
          order: 4,
          kind: "assessment",
          title: "Évaluer sa maîtrise",
          objective: "Résoudre des opérations posées sur des décimaux dans un contexte de problème.",
          status: "upcoming",
        },
      ],
    },
  },
  {
    id: "cm2-ma-gm-aires",
    slug: "aire-du-rectangle-et-du-triangle",
    levelSlug: "cm2",
    subject: "Mathématiques",
    domainSlug: "mathematiques",
    subdomainSlug: "grandeurs-mesures",
    title: "Aire du rectangle et du triangle",
    observableObjective:
      "Calculer l'aire d'un rectangle et d'un triangle en appliquant les formules.",
    successCriteria: [
      "J'identifie la base et la hauteur d'un rectangle ou d'un triangle.",
      "J'applique la formule de l'aire du rectangle (L × l).",
      "J'applique la formule de l'aire du triangle (base × hauteur ÷ 2).",
    ],
    lessonIds: [],
    status: "upcoming",
    sequence: {
      id: "seq-cm2-ma-gm-aires",
      competencyId: "cm2-ma-gm-aires",
      title: "Calculer des surfaces",
      status: "upcoming",
      steps: [
        {
          id: "step-cm2-ma-gm-aires-1",
          order: 1,
          kind: "discovery",
          title: "Comprendre ce qu'est une aire",
          objective: "Comparer des surfaces par pavage ou découpage pour construire le sens de la mesure d'aire.",
          status: "upcoming",
        },
        {
          id: "step-cm2-ma-gm-aires-2",
          order: 2,
          kind: "explicit-lesson",
          title: "Apprendre les formules",
          objective: "Retenir et comprendre les formules de l'aire du rectangle (L × l) et du triangle (base × hauteur ÷ 2).",
          status: "upcoming",
        },
        {
          id: "step-cm2-ma-gm-aires-3",
          order: 3,
          kind: "guided-practice",
          title: "Appliquer les formules",
          objective: "Calculer des aires de rectangles et de triangles à partir de dimensions données.",
          status: "upcoming",
        },
        {
          id: "step-cm2-ma-gm-aires-4",
          order: 4,
          kind: "assessment",
          title: "Évaluer sa maîtrise",
          objective: "Calculer des aires dans un problème combinant rectangle et triangle.",
          status: "upcoming",
        },
      ],
    },
  },
  {
    id: "cm2-ma-geo-symetrie-axiale",
    slug: "symetrie-axiale",
    levelSlug: "cm2",
    subject: "Mathématiques",
    domainSlug: "mathematiques",
    subdomainSlug: "geometrie",
    title: "Symétrie axiale",
    observableObjective:
      "Reconnaître et construire le symétrique d'une figure par rapport à un axe.",
    successCriteria: [
      "Je reconnais si une figure est symétrique par rapport à un axe donné.",
      "Je construis le symétrique d'un point par rapport à un axe.",
      "Je trace le symétrique d'une figure simple à l'aide de la règle et de l'équerre.",
    ],
    lessonIds: [],
    status: "upcoming",
    sequence: {
      id: "seq-cm2-ma-geo-symetrie-axiale",
      competencyId: "cm2-ma-geo-symetrie-axiale",
      title: "Tracer par symétrie",
      status: "upcoming",
      steps: [
        {
          id: "step-cm2-ma-geo-symetrie-axiale-1",
          order: 1,
          kind: "discovery",
          title: "Percevoir la symétrie axiale",
          objective: "Identifier des figures symétriques dans l'environnement et repérer leur axe de symétrie.",
          status: "upcoming",
        },
        {
          id: "step-cm2-ma-geo-symetrie-axiale-2",
          order: 2,
          kind: "explicit-lesson",
          title: "Comprendre le symétrique d'un point",
          objective: "Construire le symétrique d'un point par rapport à un axe en utilisant la règle et l'équerre.",
          status: "upcoming",
        },
        {
          id: "step-cm2-ma-geo-symetrie-axiale-3",
          order: 3,
          kind: "guided-practice",
          title: "Tracer des figures symétriques",
          objective: "Construire le symétrique de figures simples par rapport à un axe vertical, horizontal ou oblique.",
          status: "upcoming",
        },
        {
          id: "step-cm2-ma-geo-symetrie-axiale-4",
          order: 4,
          kind: "assessment",
          title: "Évaluer sa maîtrise",
          objective: "Reconnaître et construire un symétrique dans une situation nouvelle avec justification.",
          status: "upcoming",
        },
      ],
    },
  },
] as const satisfies LearningCompetency[];
