import type { LearningCompetency } from "@/content/learning-architecture-types";

export const cm2Competencies = [
  {
    id: "cm2-fr-edl-passe-simple",
    slug: "passe-simple-formes-et-emploi",
    levelSlug: "cm2",
    subject: "Français",
    domainSlug: "francais",
    subdomainSlug: "etude-de-la-langue",
    title: "Passé simple — formes et emploi",
    observableObjective:
      "Reconnaître et conjuguer les verbes des trois groupes au passé simple dans un contexte narratif.",
    successCriteria: [
      "Je reconnais le passé simple dans un texte narratif.",
      "Je conjugue un verbe du 1er groupe au passé simple.",
      "Je conjugue un verbe du 3e groupe courant (être, avoir, venir) au passé simple.",
    ],
    lessonIds: [],
    status: "upcoming",
    sequence: {
      id: "seq-cm2-fr-edl-passe-simple",
      competencyId: "cm2-fr-edl-passe-simple",
      title: "Conjuguer au passé simple",
      status: "upcoming",
      steps: [],
    },
  },
  {
    id: "cm2-fr-edl-accord-participe",
    slug: "accord-du-participe-passe-etre-avoir",
    levelSlug: "cm2",
    subject: "Français",
    domainSlug: "francais",
    subdomainSlug: "etude-de-la-langue",
    title: "Accord du participe passé avec être et avoir",
    observableObjective:
      "Appliquer la règle d'accord du participe passé avec les auxiliaires être et avoir (cas de base).",
    successCriteria: [
      "Je distingue les auxiliaires être et avoir.",
      "J'accorde le participe passé avec le sujet quand l'auxiliaire est être.",
      "Je n'accorde pas le participe passé avec avoir (cas de base, sans COD antéposé).",
    ],
    lessonIds: [],
    status: "upcoming",
    sequence: {
      id: "seq-cm2-fr-edl-accord-participe",
      competencyId: "cm2-fr-edl-accord-participe",
      title: "Être ou avoir : accorder le participe",
      status: "upcoming",
      steps: [],
    },
  },
  {
    id: "cm2-fr-edl-nature-fonction",
    slug: "nature-et-fonction-gn-cod-coi",
    levelSlug: "cm2",
    subject: "Français",
    domainSlug: "francais",
    subdomainSlug: "etude-de-la-langue",
    title: "Nature et fonction : GN, COD, COI",
    observableObjective:
      "Identifier la nature (groupe nominal) et la fonction (COD ou COI) d'un groupe dans la phrase.",
    successCriteria: [
      "Je repère un groupe nominal dans une phrase.",
      "Je distingue le COD du COI à l'aide des questions (quoi ? / à qui ?).",
      "Je justifie la fonction en posant la question appropriée.",
    ],
    lessonIds: [],
    status: "upcoming",
    sequence: {
      id: "seq-cm2-fr-edl-nature-fonction",
      competencyId: "cm2-fr-edl-nature-fonction",
      title: "Nommer et fonctionner",
      status: "upcoming",
      steps: [],
    },
  },
  {
    id: "cm2-fr-lc-implicite",
    slug: "comprendre-limplicite-et-les-sous-entendus",
    levelSlug: "cm2",
    subject: "Français",
    domainSlug: "francais",
    subdomainSlug: "lecture-comprehension",
    title: "Comprendre l'implicite et les sous-entendus",
    observableObjective:
      "Interpréter ce qu'un texte laisse entendre sans le dire en s'appuyant sur des indices textuels.",
    successCriteria: [
      "Je repère une information non dite dans le texte.",
      "Je cite les indices qui me permettent de l'inférer.",
      "Je formule le sous-entendu en une phrase justifiée.",
    ],
    lessonIds: [],
    status: "upcoming",
    sequence: {
      id: "seq-cm2-fr-lc-implicite",
      competencyId: "cm2-fr-lc-implicite",
      title: "Lire entre les lignes",
      status: "upcoming",
      steps: [],
    },
  },
  {
    id: "cm2-fr-ec-texte-argumentatif",
    slug: "rediger-un-texte-argumentatif-court",
    levelSlug: "cm2",
    subject: "Français",
    domainSlug: "francais",
    subdomainSlug: "ecriture",
    title: "Rédiger un texte argumentatif court",
    observableObjective:
      "Défendre un point de vue à l'écrit en formulant au moins deux arguments illustrés d'exemples.",
    successCriteria: [
      "J'annonce clairement mon point de vue.",
      "Je donne au moins deux arguments distincts.",
      "J'illustre chaque argument par un exemple.",
    ],
    lessonIds: [],
    status: "upcoming",
    sequence: {
      id: "seq-cm2-fr-ec-texte-argumentatif",
      competencyId: "cm2-fr-ec-texte-argumentatif",
      title: "Convaincre par l'écrit",
      status: "upcoming",
      steps: [],
    },
  },
  {
    id: "cm2-ma-num-decimaux",
    slug: "nombres-decimaux-lire-ecrire-comparer",
    levelSlug: "cm2",
    subject: "Mathématiques",
    domainSlug: "mathematiques",
    subdomainSlug: "numeration",
    title: "Nombres décimaux — lire, écrire, comparer",
    observableObjective:
      "Lire, écrire et comparer des nombres décimaux en s'appuyant sur la valeur positionnelle des chiffres.",
    successCriteria: [
      "Je lis un nombre décimal et je nomme chaque chiffre par sa position.",
      "J'écris en chiffres un nombre décimal dicté à l'oral.",
      "Je compare deux nombres décimaux et je justifie.",
    ],
    lessonIds: [],
    status: "upcoming",
    sequence: {
      id: "seq-cm2-ma-num-decimaux",
      competencyId: "cm2-ma-num-decimaux",
      title: "Lire et écrire les décimaux",
      status: "upcoming",
      steps: [],
    },
  },
  {
    id: "cm2-ma-num-fractions-decimaux",
    slug: "fractions-et-decimaux-equivalences",
    levelSlug: "cm2",
    subject: "Mathématiques",
    domainSlug: "mathematiques",
    subdomainSlug: "numeration",
    title: "Fractions et décimaux — équivalences",
    observableObjective:
      "Passer d'une fraction simple à l'écriture décimale et inversement.",
    successCriteria: [
      "Je convertis une fraction à dénominateur 10 ou 100 en décimal.",
      "J'écris un décimal simple sous forme de fraction.",
      "Je place une fraction ou un décimal sur une droite graduée.",
    ],
    lessonIds: [],
    status: "upcoming",
    sequence: {
      id: "seq-cm2-ma-num-fractions-decimaux",
      competencyId: "cm2-ma-num-fractions-decimaux",
      title: "Passer d'une écriture à l'autre",
      status: "upcoming",
      steps: [],
    },
  },
  {
    id: "cm2-ma-cal-operations-decimaux",
    slug: "operations-sur-les-decimaux",
    levelSlug: "cm2",
    subject: "Mathématiques",
    domainSlug: "mathematiques",
    subdomainSlug: "calcul-pose",
    title: "Opérations sur les décimaux",
    observableObjective:
      "Poser et calculer des additions, soustractions et multiplications impliquant des nombres décimaux.",
    successCriteria: [
      "J'aligne les virgules lors de la pose de l'opération.",
      "Je calcule une addition ou soustraction de décimaux posée.",
      "Je pose et calcule une multiplication par un entier avec un résultat décimal.",
    ],
    lessonIds: [],
    status: "upcoming",
    sequence: {
      id: "seq-cm2-ma-cal-operations-decimaux",
      competencyId: "cm2-ma-cal-operations-decimaux",
      title: "Calculer avec les décimaux",
      status: "upcoming",
      steps: [],
    },
  },
  {
    id: "cm2-ma-gm-aires",
    slug: "aire-du-rectangle-et-du-triangle",
    levelSlug: "cm2",
    subject: "Mathématiques",
    domainSlug: "mathematiques",
    subdomainSlug: "grandeurs-mesures",
    title: "Aire du rectangle et du triangle",
    observableObjective:
      "Calculer l'aire d'un rectangle et d'un triangle en appliquant les formules.",
    successCriteria: [
      "J'identifie la base et la hauteur d'un rectangle ou d'un triangle.",
      "J'applique la formule de l'aire du rectangle (L × l).",
      "J'applique la formule de l'aire du triangle (base × hauteur ÷ 2).",
    ],
    lessonIds: [],
    status: "upcoming",
    sequence: {
      id: "seq-cm2-ma-gm-aires",
      competencyId: "cm2-ma-gm-aires",
      title: "Calculer des surfaces",
      status: "upcoming",
      steps: [],
    },
  },
  {
    id: "cm2-ma-geo-symetrie-axiale",
    slug: "symetrie-axiale",
    levelSlug: "cm2",
    subject: "Mathématiques",
    domainSlug: "mathematiques",
    subdomainSlug: "geometrie",
    title: "Symétrie axiale",
    observableObjective:
      "Reconnaître et construire le symétrique d'une figure par rapport à un axe.",
    successCriteria: [
      "Je reconnais si une figure est symétrique par rapport à un axe donné.",
      "Je construis le symétrique d'un point par rapport à un axe.",
      "Je trace le symétrique d'une figure simple à l'aide de la règle et de l'équerre.",
    ],
    lessonIds: [],
    status: "upcoming",
    sequence: {
      id: "seq-cm2-ma-geo-symetrie-axiale",
      competencyId: "cm2-ma-geo-symetrie-axiale",
      title: "Tracer par symétrie",
      status: "upcoming",
      steps: [],
    },
  },
] as const satisfies LearningCompetency[];
