// Registre des séquences CM2 — couche de planification pédagogique.
// Règle absolue : 1 séquence = 1 compétence principale.
// Ce fichier ne contient aucun contenu de séance, leçon, exercice ou corrigé.
// Les champs optionnels (felixRole, visualToCreate) servent uniquement au pilotage.

export type Cm2SequenceStatus = "available" | "in-progress" | "upcoming";

export type Cm2Sequence = {
  slug: string;
  title: string;
  domain: string;
  subdomain: string;
  skill: string;
  status: Cm2SequenceStatus;
  level: "CM2";
  shortDescription?: string;
  teacherReference?: string;
  felixRole?: string;
  visualToCreate?: string;
};

// ── Français ──────────────────────────────────────────────────────────────────

const francaisSequences: Cm2Sequence[] = [
  // Lecture et compréhension — Inférences
  {
    slug: "fr-lc-reperer-indices",
    title: "Repérer les indices dans un texte",
    domain: "Lecture et compréhension",
    subdomain: "Inférences",
    skill: "Prélever des indices explicites et implicites dans un texte court.",
    status: "in-progress",
    level: "CM2",
    shortDescription: "Identifier les mots et groupes qui portent une information utile.",
    felixRole: "Enquêteur qui surligne les indices sur un document.",
    visualToCreate: "Fiche méthode : texte + zone d'indices",
  },
  {
    slug: "fr-lc-explicite-implicite",
    title: "Distinguer information explicite et information implicite",
    domain: "Lecture et compréhension",
    subdomain: "Inférences",
    skill: "Différencier ce qui est dit directement de ce qui est à déduire.",
    status: "in-progress",
    level: "CM2",
    shortDescription: "Classer les informations selon leur nature dans un tableau.",
    felixRole: "Lecteur qui trie les indices avant de conclure.",
    visualToCreate: "Tableau deux colonnes : explicite / implicite",
  },
  {
    slug: "fr-lc-faire-inference",
    title: "Construire une inférence à partir des indices",
    domain: "Lecture et compréhension",
    subdomain: "Inférences",
    skill: "Formuler une conclusion déduite d'indices relevés dans le texte.",
    status: "upcoming",
    level: "CM2",
    felixRole: "Détective qui relie les indices pour formuler une hypothèse.",
    visualToCreate: "Fiche : indices → hypothèse → justification",
  },
  {
    slug: "fr-lc-justifier-reponse",
    title: "Justifier une réponse par un passage du texte",
    domain: "Lecture et compréhension",
    subdomain: "Justification par le texte",
    skill: "Appuyer une réponse sur un extrait précis du texte.",
    status: "upcoming",
    level: "CM2",
    shortDescription: "Rédiger une phrase-réponse avec ancrage textuel.",
    felixRole: "Guide qui vérifie que chaque réponse cite sa source.",
    visualToCreate: "Modèle de phrase : « Je pense que… parce que dans le texte… »",
  },
  {
    slug: "fr-lc-idee-principale",
    title: "Identifier l'idée principale d'un texte",
    domain: "Lecture et compréhension",
    subdomain: "Compréhension globale",
    skill: "Formuler l'idée centrale d'un texte court en une phrase.",
    status: "upcoming",
    level: "CM2",
    teacherReference: "Lecture stratégique · CM2 Cycle 3",
    felixRole: "Lecteur qui résume l'essentiel avant de commenter.",
    visualToCreate: "Fiche : texte → idée principale en une phrase",
  },
  {
    slug: "fr-lc-fait-opinion",
    title: "Distinguer fait, opinion et interprétation",
    domain: "Lecture et compréhension",
    subdomain: "Posture critique",
    skill: "Reconnaître la nature d'une information dans un texte.",
    status: "upcoming",
    level: "CM2",
    felixRole: "Analyste qui étiquette chaque affirmation avant de valider.",
    visualToCreate: "Tableau trois colonnes : fait / opinion / interprétation",
  },

  // Production d'écrit
  {
    slug: "fr-pe-planifier",
    title: "Planifier un texte avant de l'écrire",
    domain: "Production d'écrit",
    subdomain: "Organisation du texte",
    skill: "Construire un plan en trois temps avant la rédaction.",
    status: "upcoming",
    level: "CM2",
    shortDescription: "Organiser les idées en amont pour structurer le brouillon.",
    felixRole: "Explorateur qui trace une carte avant de partir.",
    visualToCreate: "Fiche plan : début / développement / fin",
  },
  {
    slug: "fr-pe-utiliser-connecteurs",
    title: "Utiliser les connecteurs logiques",
    domain: "Production d'écrit",
    subdomain: "Cohérence et enchaînement",
    skill: "Relier des idées avec des connecteurs adaptés à leur relation logique.",
    status: "upcoming",
    level: "CM2",
    teacherReference: "Liste de connecteurs par type : chronologique, causal, oppositif",
    felixRole: "Messager qui relie les parties d'un rapport.",
    visualToCreate: "Tableau des connecteurs par fonction",
  },
  {
    slug: "fr-pe-reviser-brouillon",
    title: "Réviser son brouillon avec des critères",
    domain: "Production d'écrit",
    subdomain: "Révision et amélioration",
    skill: "Améliorer un texte en ciblant un critère à la fois.",
    status: "upcoming",
    level: "CM2",
    felixRole: "Correcteur qui relit avec une grille avant de valider.",
    visualToCreate: "Grille de relecture courte : consigne / ordre / ponctuation",
  },

  // Étude de la langue — Grammaire
  {
    slug: "fr-edl-reperer-verbe",
    title: "Repérer le verbe conjugué dans une phrase",
    domain: "Étude de la langue",
    subdomain: "Grammaire de la phrase",
    skill: "Identifier le verbe conjugué en appliquant le test de conjugaison.",
    status: "upcoming",
    level: "CM2",
    felixRole: "Analyste qui code les groupes dans une phrase.",
    visualToCreate: "Fiche codage : encadrer le verbe, souligner le sujet",
  },
  {
    slug: "fr-edl-identifier-sujet",
    title: "Identifier le groupe sujet",
    domain: "Étude de la langue",
    subdomain: "Grammaire de la phrase",
    skill: "Trouver le groupe sujet en posant la question « Qui est-ce qui ? ».",
    status: "upcoming",
    level: "CM2",
    felixRole: "Enquêteur qui interroge la phrase pour trouver le responsable.",
    visualToCreate: "Phrase annotée avec codage sujet / verbe / compléments",
  },
  {
    slug: "fr-edl-accords-sujet-verbe",
    title: "Appliquer l'accord sujet-verbe",
    domain: "Étude de la langue",
    subdomain: "Accords",
    skill: "Accorder le verbe avec son sujet, même éloigné ou inversé.",
    status: "upcoming",
    level: "CM2",
    teacherReference: "Cas particuliers : sujet inversé, sujet collectif",
    felixRole: "Vérificateur qui contrôle les accords avant de soumettre.",
    visualToCreate: "Fiche : sujet → genre, nombre → accord du verbe",
  },
  {
    slug: "fr-edl-accords-dans-gn",
    title: "Accorder dans le groupe nominal",
    domain: "Étude de la langue",
    subdomain: "Accords",
    skill: "Accorder déterminant, nom et adjectif au sein d'un groupe nominal.",
    status: "upcoming",
    level: "CM2",
    felixRole: "Détective qui vérifie la cohérence de chaque groupe.",
    visualToCreate: "Fiche : GN → chaîne d'accord déterminant / nom / adjectif",
  },

  // Oral
  {
    slug: "fr-oral-reformuler",
    title: "Reformuler une idée avec ses propres mots",
    domain: "Oral",
    subdomain: "Prise de parole",
    skill: "Restituer une information en changeant la formulation sans en changer le sens.",
    status: "upcoming",
    level: "CM2",
    felixRole: "Messager qui retranscrit fidèlement ce qu'il a compris.",
    visualToCreate: "Fiche : message d'origine → reformulation",
  },

  // Lecture — types de textes et stratégies
  {
    slug: "fr-lc-fluidite",
    title: "Lire avec fluidité un texte long",
    domain: "Lecture et compréhension",
    subdomain: "Fluidité de lecture",
    skill: "Lire un texte de plusieurs paragraphes à voix haute avec précision et expression.",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "fr-lc-texte-documentaire",
    title: "Comprendre un texte documentaire",
    domain: "Lecture et compréhension",
    subdomain: "Textes documentaires",
    skill: "Extraire les informations clés d'un texte documentaire et en identifier la structure.",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "fr-lc-intentions-auteur",
    title: "Interpréter les intentions d'un auteur",
    domain: "Lecture et compréhension",
    subdomain: "Intentions de l'auteur",
    skill: "Identifier les choix d'écriture d'un auteur et en déduire ses intentions.",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "fr-lc-resumer",
    title: "Résumer un texte",
    domain: "Lecture et compréhension",
    subdomain: "Résumé et comparaison",
    skill: "Reformuler l'essentiel d'un texte en quelques phrases sans paraphraser.",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "fr-lc-comparer-documents",
    title: "Comparer plusieurs documents sur un même sujet",
    domain: "Lecture et compréhension",
    subdomain: "Résumé et comparaison",
    skill: "Rapprocher des informations issues de plusieurs documents pour les confronter.",
    status: "upcoming",
    level: "CM2",
  },

  // Production d'écrit — types de textes
  {
    slug: "fr-pe-recit-structure",
    title: "Produire un récit structuré",
    domain: "Production d'écrit",
    subdomain: "Types de textes",
    skill: "Rédiger un récit avec une situation initiale, une péripétie et une résolution.",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "fr-pe-texte-argumentatif",
    title: "Produire un texte argumentatif simple",
    domain: "Production d'écrit",
    subdomain: "Types de textes",
    skill: "Rédiger un texte exprimant une opinion et l'appuyant sur deux arguments.",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "fr-pe-texte-explicatif",
    title: "Produire un texte explicatif",
    domain: "Production d'écrit",
    subdomain: "Types de textes",
    skill: "Rédiger un texte qui explique un phénomène en organisant les informations logiquement.",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "fr-pe-enrichir-reviser",
    title: "Enrichir et réviser son écrit",
    domain: "Production d'écrit",
    subdomain: "Révision et amélioration",
    skill: "Améliorer un texte en enrichissant le vocabulaire et en corrigeant les erreurs.",
    status: "upcoming",
    level: "CM2",
  },

  // Grammaire
  {
    slug: "fr-edl-phrase-simple-complexe",
    title: "Distinguer phrase simple et phrase complexe",
    domain: "Étude de la langue",
    subdomain: "Grammaire de la phrase",
    skill: "Identifier le nombre de propositions dans une phrase et reconnaître sa complexité.",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "fr-edl-fonctions-phrase",
    title: "Identifier les fonctions dans la phrase",
    domain: "Étude de la langue",
    subdomain: "Grammaire de la phrase",
    skill: "Reconnaître sujet, COD, COI et compléments circonstanciels dans des phrases variées.",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "fr-edl-classes-grammaticales",
    title: "Identifier les classes grammaticales",
    domain: "Étude de la langue",
    subdomain: "Nature des mots",
    skill: "Classer les mots selon leur catégorie grammaticale (nom, verbe, adjectif, adverbe…).",
    status: "upcoming",
    level: "CM2",
  },

  // Conjugaison
  {
    slug: "fr-edl-conjuguer-present",
    title: "Conjuguer au présent de l'indicatif",
    domain: "Étude de la langue",
    subdomain: "Conjugaison",
    skill: "Conjuguer des verbes des 1er, 2e et 3e groupes au présent de l'indicatif.",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "fr-edl-conjuguer-imparfait",
    title: "Conjuguer à l'imparfait",
    domain: "Étude de la langue",
    subdomain: "Conjugaison",
    skill: "Conjuguer des verbes courants à l'imparfait de l'indicatif.",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "fr-edl-conjuguer-futur",
    title: "Conjuguer au futur simple",
    domain: "Étude de la langue",
    subdomain: "Conjugaison",
    skill: "Conjuguer des verbes courants au futur simple de l'indicatif.",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "fr-edl-conjuguer-passe-compose",
    title: "Conjuguer au passé composé",
    domain: "Étude de la langue",
    subdomain: "Conjugaison",
    skill: "Conjuguer des verbes au passé composé avec les auxiliaires être et avoir.",
    status: "upcoming",
    level: "CM2",
  },

  // Orthographe
  {
    slug: "fr-orth-homophones",
    title: "Orthographier les homophones grammaticaux fréquents",
    domain: "Étude de la langue",
    subdomain: "Orthographe d'usage",
    skill: "Distinguer et orthographier correctement les homophones les plus fréquents (a/à, et/est, son/sont, ou/où, ce/se…).",
    status: "upcoming",
    level: "CM2",
  },

  // Lexique
  {
    slug: "fr-lex-synonymes-antonymes",
    title: "Utiliser synonymes et antonymes",
    domain: "Lexique",
    subdomain: "Sens des mots",
    skill: "Identifier et utiliser des synonymes et des antonymes pour enrichir ses écrits.",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "fr-lex-familles-champs",
    title: "Utiliser familles de mots et champs lexicaux",
    domain: "Lexique",
    subdomain: "Formation des mots",
    skill: "Regrouper des mots par famille et constituer un champ lexical autour d'un thème.",
    status: "upcoming",
    level: "CM2",
  },
];

// ── Mathématiques ─────────────────────────────────────────────────────────────

const mathematiquesSequences: Cm2Sequence[] = [
  // Nombres et calcul
  {
    slug: "ma-nc-calcul-mental-strategies",
    title: "Choisir une stratégie de calcul mental",
    domain: "Nombres et calcul",
    subdomain: "Calcul mental raisonné",
    skill: "Sélectionner la stratégie la plus efficace selon les nombres en jeu.",
    status: "in-progress",
    level: "CM2",
    shortDescription: "Décomposer, regrouper ou utiliser un complément selon la situation.",
    teacherReference: "Comparer plusieurs procédures au tableau avant de valider",
    felixRole: "Stratège qui choisit la méthode avant d'agir.",
    visualToCreate: "Fiche : calcul → stratégie utilisée → vérification",
  },
  {
    slug: "ma-nc-calcul-mental-expliquer",
    title: "Expliquer sa procédure de calcul mental",
    domain: "Nombres et calcul",
    subdomain: "Calcul mental raisonné",
    skill: "Verbaliser les étapes d'un calcul mental pour le rendre communicable.",
    status: "upcoming",
    level: "CM2",
    felixRole: "Expert qui justifie chaque étape de son raisonnement.",
    visualToCreate: "Fiche : calcul → étapes → phrase d'explication",
  },
  {
    slug: "ma-nc-multiplier-grands-nombres",
    title: "Multiplier des nombres entiers",
    domain: "Nombres et calcul",
    subdomain: "Calcul posé",
    skill: "Poser et effectuer une multiplication avec des nombres à plusieurs chiffres.",
    status: "upcoming",
    level: "CM2",
    teacherReference: "Multiplication posée : disposition, retenues, vérification",
    felixRole: "Mécanicien qui monte les étapes une à une.",
    visualToCreate: "Fiche : disposition de la multiplication posée",
  },
  {
    slug: "ma-nc-diviser-entiers",
    title: "Diviser un entier par un entier",
    domain: "Nombres et calcul",
    subdomain: "Calcul posé",
    skill: "Poser une division euclidienne et interpréter quotient et reste.",
    status: "upcoming",
    level: "CM2",
    teacherReference: "Distinguer quotient exact et quotient avec reste",
    felixRole: "Partageur qui distribue équitablement et comptabilise le reste.",
    visualToCreate: "Fiche : division posée + sens du quotient et du reste",
  },
  {
    slug: "ma-nc-comparer-fractions",
    title: "Comparer des fractions simples",
    domain: "Nombres et calcul",
    subdomain: "Fractions",
    skill: "Ordonner des fractions en utilisant le même dénominateur ou la droite graduée.",
    status: "upcoming",
    level: "CM2",
    felixRole: "Cartographe qui place les fractions sur une droite.",
    visualToCreate: "Fiche : droite numérique graduée en fractions",
  },

  // Résolution de problèmes
  {
    slug: "ma-pb-identifier-donnees",
    title: "Identifier les données utiles dans un problème",
    domain: "Résolution de problèmes",
    subdomain: "Lecture de l'énoncé",
    skill: "Séparer les données nécessaires des données inutiles ou pièges.",
    status: "in-progress",
    level: "CM2",
    shortDescription: "Lire un énoncé en ciblant la question et les informations nécessaires.",
    felixRole: "Détective qui trie les indices avant d'enquêter.",
    visualToCreate: "Fiche : données utiles / données inutiles / question",
  },
  {
    slug: "ma-pb-choisir-operation",
    title: "Choisir l'opération adaptée à la situation",
    domain: "Résolution de problèmes",
    subdomain: "Modélisation",
    skill: "Relier la situation mathématique à l'opération qui la modélise.",
    status: "upcoming",
    level: "CM2",
    teacherReference: "Tableau de correspondance : réunion → addition, partage → division…",
    felixRole: "Ingénieur qui modélise la situation avant de calculer.",
    visualToCreate: "Carte des situations → opérations",
  },
  {
    slug: "ma-pb-resoudre-etapes",
    title: "Résoudre un problème à plusieurs étapes",
    domain: "Résolution de problèmes",
    subdomain: "Problèmes complexes",
    skill: "Décomposer un problème en sous-questions pour l'aborder étape par étape.",
    status: "upcoming",
    level: "CM2",
    felixRole: "Explorateur qui avance étape par étape vers la solution.",
    visualToCreate: "Fiche : étape 1 / étape 2 / résultat final",
  },
  {
    slug: "ma-pb-verifier-coherence",
    title: "Vérifier la cohérence d'un résultat",
    domain: "Résolution de problèmes",
    subdomain: "Validation",
    skill: "Estimer si un résultat est plausible et en vérifier la cohérence.",
    status: "upcoming",
    level: "CM2",
    teacherReference: "Ordre de grandeur, opération inverse, unité du résultat",
    felixRole: "Vérificateur qui contrôle le résultat avant de rendre le rapport.",
    visualToCreate: "Fiche : résultat → test de cohérence",
  },

  // Grandeurs et mesures
  {
    slug: "ma-gm-conversions-longueurs",
    title: "Convertir des unités de longueur",
    domain: "Grandeurs et mesures",
    subdomain: "Longueurs",
    skill: "Passer d'une unité à une autre dans le système métrique des longueurs.",
    status: "upcoming",
    level: "CM2",
    felixRole: "Cartographe qui exprime les distances dans l'unité adaptée.",
    visualToCreate: "Tableau de conversions : km / hm / dam / m / dm / cm / mm",
  },
  {
    slug: "ma-gm-perimetre-aire",
    title: "Distinguer périmètre et aire",
    domain: "Grandeurs et mesures",
    subdomain: "Surfaces",
    skill: "Différencier le contour d'une figure de la surface qu'elle occupe.",
    status: "upcoming",
    level: "CM2",
    felixRole: "Architecte qui mesure les murs d'une salle, puis son sol.",
    visualToCreate: "Fiche : figure → périmètre (contour) vs aire (intérieur)",
  },

  // Grands nombres
  {
    slug: "ma-nc-grands-nombres-lire",
    title: "Lire et écrire les grands nombres",
    domain: "Nombres et calcul",
    subdomain: "Grands nombres",
    skill: "Lire, écrire et décomposer des nombres entiers jusqu'au milliard.",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "ma-nc-grands-nombres-comparer",
    title: "Comparer et ranger des grands nombres",
    domain: "Nombres et calcul",
    subdomain: "Grands nombres",
    skill: "Ordonner des grands nombres en utilisant les signes < et >.",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "ma-nc-encadrer",
    title: "Encadrer un nombre entre deux valeurs",
    domain: "Nombres et calcul",
    subdomain: "Grands nombres",
    skill: "Encadrer un nombre entier ou décimal entre deux multiples d'une unité donnée.",
    status: "upcoming",
    level: "CM2",
  },

  // Fractions complémentaires
  {
    slug: "ma-nc-fractions-utiliser",
    title: "Utiliser les fractions simples",
    domain: "Nombres et calcul",
    subdomain: "Fractions",
    skill: "Interpréter une fraction comme un partage ou une mesure et l'utiliser dans une situation.",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "ma-nc-fractions-droite",
    title: "Placer des fractions sur une droite graduée",
    domain: "Nombres et calcul",
    subdomain: "Fractions",
    skill: "Positionner des fractions simples sur une droite numérique graduée.",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "ma-nc-fraction-decimale",
    title: "Passer d'une fraction décimale à un nombre décimal",
    domain: "Nombres et calcul",
    subdomain: "Fractions",
    skill: "Convertir une fraction décimale (dixièmes, centièmes) en écriture décimale.",
    status: "upcoming",
    level: "CM2",
  },

  // Nombres décimaux
  {
    slug: "ma-nc-decimaux-lire",
    title: "Lire, écrire et comparer des nombres décimaux",
    domain: "Nombres et calcul",
    subdomain: "Nombres décimaux",
    skill: "Lire, écrire et ordonner des nombres à virgule en utilisant les rangs décimaux.",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "ma-nc-decimaux-additionner",
    title: "Additionner et soustraire des nombres décimaux",
    domain: "Nombres et calcul",
    subdomain: "Nombres décimaux",
    skill: "Poser et calculer une addition ou soustraction de décimaux en alignant les virgules.",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "ma-nc-decimaux-multiplier",
    title: "Multiplier des nombres décimaux simples",
    domain: "Nombres et calcul",
    subdomain: "Nombres décimaux",
    skill: "Multiplier un nombre décimal par un entier et placer la virgule correctement.",
    status: "upcoming",
    level: "CM2",
  },

  // Proportionnalité
  {
    slug: "ma-pb-proportionnalite",
    title: "Reconnaître et utiliser la proportionnalité",
    domain: "Résolution de problèmes",
    subdomain: "Proportionnalité",
    skill: "Identifier une situation de proportionnalité et résoudre un problème en utilisant le coefficient.",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "ma-pb-pourcentages",
    title: "Utiliser les pourcentages simples",
    domain: "Résolution de problèmes",
    subdomain: "Proportionnalité",
    skill: "Calculer 50 %, 25 % et 10 % d'une valeur dans des situations concrètes.",
    status: "upcoming",
    level: "CM2",
  },

  // Grandeurs
  {
    slug: "ma-gm-conversions-masses",
    title: "Convertir des unités de masse",
    domain: "Grandeurs et mesures",
    subdomain: "Masses",
    skill: "Passer d'une unité de masse à une autre dans le système métrique.",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "ma-gm-conversions-contenances",
    title: "Convertir des unités de contenance",
    domain: "Grandeurs et mesures",
    subdomain: "Contenances",
    skill: "Passer d'une unité de contenance à une autre (L, dL, cL, mL).",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "ma-gm-durees",
    title: "Calculer des durées",
    domain: "Grandeurs et mesures",
    subdomain: "Durées",
    skill: "Calculer une durée entre deux moments en utilisant les conversions d'unités de temps.",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "ma-gm-perimetre-calculer",
    title: "Calculer le périmètre d'une figure",
    domain: "Grandeurs et mesures",
    subdomain: "Surfaces",
    skill: "Calculer le périmètre d'un polygone quelconque en additionnant ses côtés.",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "ma-gm-aire-rectangle-carre",
    title: "Calculer l'aire d'un carré et d'un rectangle",
    domain: "Grandeurs et mesures",
    subdomain: "Surfaces",
    skill: "Appliquer les formules d'aire du carré et du rectangle.",
    status: "upcoming",
    level: "CM2",
  },

  // Géométrie
  {
    slug: "ma-geo-figures",
    title: "Reconnaître et tracer des figures géométriques",
    domain: "Espace et géométrie",
    subdomain: "Figures planes",
    skill: "Identifier et construire des quadrilatères, triangles et cercles avec les instruments.",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "ma-geo-angles",
    title: "Identifier et comparer des angles",
    domain: "Espace et géométrie",
    subdomain: "Angles",
    skill: "Reconnaître angles droits, aigus et obtus, et les mesurer avec un rapporteur.",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "ma-geo-symetrie",
    title: "Utiliser la symétrie axiale",
    domain: "Espace et géométrie",
    subdomain: "Symétrie",
    skill: "Construire le symétrique d'une figure par rapport à un axe donné.",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "ma-geo-reperage-plan",
    title: "Se repérer dans un plan avec des coordonnées",
    domain: "Espace et géométrie",
    subdomain: "Repérage dans l'espace",
    skill: "Lire et placer des points dans un repère orthogonal.",
    status: "upcoming",
    level: "CM2",
  },

  // Données
  {
    slug: "ma-do-tableaux-graphiques",
    title: "Lire et construire des tableaux ou graphiques simples",
    domain: "Organisation et gestion de données",
    subdomain: "Tableaux et graphiques",
    skill: "Lire un tableau de données, construire un diagramme en barres ou circulaire simple.",
    status: "upcoming",
    level: "CM2",
  },
];

// ── Histoire-Géographie ───────────────────────────────────────────────────────

const histoireGeoSequences: Cm2Sequence[] = [
  // Histoire — Lecture de documents
  {
    slug: "hg-hi-identifier-document",
    title: "Identifier la nature d'un document historique",
    domain: "Histoire",
    subdomain: "Lecture de sources",
    skill: "Déterminer si un document est une archive, un témoignage, une image ou une carte.",
    status: "in-progress",
    level: "CM2",
    shortDescription: "Classer le document selon sa nature avant de l'interpréter.",
    felixRole: "Archiviste qui étiquette les documents avant de les lire.",
    visualToCreate: "Fiche d'identification : nature / date / auteur ou source",
  },
  {
    slug: "hg-hi-contextualiser-document",
    title: "Contextualiser un document dans son époque",
    domain: "Histoire",
    subdomain: "Lecture de sources",
    skill: "Relier la date et le lieu d'un document à une période historique connue.",
    status: "upcoming",
    level: "CM2",
    teacherReference: "Frise chronologique Cycle 3 : Antiquité / Moyen Âge / Époque moderne / Époque contemporaine",
    felixRole: "Historien qui place chaque découverte sur la frise.",
    visualToCreate: "Frise chronologique simplifiée avec repères",
  },
  {
    slug: "hg-hi-relever-indices",
    title: "Relever les indices d'un document historique",
    domain: "Histoire",
    subdomain: "Analyse de sources",
    skill: "Prélever les informations utiles d'un document pour répondre à une question.",
    status: "upcoming",
    level: "CM2",
    felixRole: "Détective qui surligne les preuves dans une archive.",
    visualToCreate: "Fiche : document → indices → ce qu'ils apprennent",
  },
  {
    slug: "hg-hi-situer-chronologie",
    title: "Situer un événement dans la chronologie",
    domain: "Histoire",
    subdomain: "Chronologie",
    skill: "Placer un événement sur une frise en distinguant siècle, période et repère.",
    status: "upcoming",
    level: "CM2",
    felixRole: "Cartographe du temps qui positionne chaque découverte.",
    visualToCreate: "Frise à compléter avec événements CM2",
  },

  // Géographie — Espaces et cartes
  {
    slug: "hg-ge-lire-carte",
    title: "Lire une carte avec sa légende",
    domain: "Géographie",
    subdomain: "Lecture de cartes",
    skill: "Utiliser le titre, l'orientation et la légende pour comprendre une carte.",
    status: "in-progress",
    level: "CM2",
    shortDescription: "Identifier les éléments d'une carte avant de localiser les lieux.",
    felixRole: "Explorateur qui déchiffre une carte avant de tracer son itinéraire.",
    visualToCreate: "Carte annotée : titre / rose des vents / légende / échelle",
  },
  {
    slug: "hg-ge-localiser-points-cardinaux",
    title: "Localiser des lieux avec les points cardinaux",
    domain: "Géographie",
    subdomain: "Repérage spatial",
    skill: "Décrire la position d'un lieu par rapport à un autre avec le vocabulaire géographique.",
    status: "upcoming",
    level: "CM2",
    felixRole: "Navigateur qui guide son équipe avec une boussole.",
    visualToCreate: "Fiche : carte + rose des vents + questions de localisation",
  },
  {
    slug: "hg-ge-decrire-espace",
    title: "Décrire l'organisation d'un espace",
    domain: "Géographie",
    subdomain: "Organisation des espaces",
    skill: "Expliquer comment un espace est structuré en identifiant ses éléments caractéristiques.",
    status: "upcoming",
    level: "CM2",
    felixRole: "Géographe qui présente un territoire à son équipe.",
    visualToCreate: "Fiche descriptive : espace → éléments naturels / humains",
  },

  // Histoire — périodes
  {
    slug: "hg-hi-antiquite",
    title: "Comprendre l'héritage de l'Antiquité",
    domain: "Histoire",
    subdomain: "Périodes historiques",
    skill: "Identifier les principales civilisations antiques (Rome, Grèce) et leurs apports.",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "hg-hi-moyen-age",
    title: "Comprendre le Moyen Âge",
    domain: "Histoire",
    subdomain: "Périodes historiques",
    skill: "Caractériser la société médiévale et identifier des repères du Moyen Âge.",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "hg-hi-temps-modernes",
    title: "Comprendre les Temps modernes",
    domain: "Histoire",
    subdomain: "Périodes historiques",
    skill: "Situer les Temps modernes et leurs caractéristiques (exploration, monarchie, religions).",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "hg-hi-revolution",
    title: "Étudier la Révolution française",
    domain: "Histoire",
    subdomain: "Révolution et République",
    skill: "Identifier les causes, le déroulement et les conséquences de la Révolution de 1789.",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "hg-hi-republique",
    title: "Comprendre la République française",
    domain: "Histoire",
    subdomain: "Révolution et République",
    skill: "Expliquer comment la République s'est installée et quels principes la fondent.",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "hg-hi-ecole-republique",
    title: "Étudier l'école de la République",
    domain: "Histoire",
    subdomain: "Révolution et République",
    skill: "Comprendre les lois Ferry et l'importance de l'école laïque et obligatoire.",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "hg-hi-guerres-mondiales",
    title: "Comprendre les guerres mondiales à hauteur d'élève",
    domain: "Histoire",
    subdomain: "XXe siècle",
    skill: "Situer les deux conflits mondiaux et identifier leurs principales conséquences.",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "hg-hi-traces-documents",
    title: "Identifier des traces et documents historiques",
    domain: "Histoire",
    subdomain: "Analyse de sources",
    skill: "Distinguer des types de documents historiques et comprendre leur utilité pour l'historien.",
    status: "upcoming",
    level: "CM2",
  },

  // Géographie — compléments
  {
    slug: "hg-ge-france",
    title: "Se repérer sur une carte de France",
    domain: "Géographie",
    subdomain: "Repérage spatial",
    skill: "Localiser les grandes régions, fleuves et reliefs de France sur une carte.",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "hg-ge-europe-monde",
    title: "Se repérer sur une carte d'Europe et du monde",
    domain: "Géographie",
    subdomain: "Repérage spatial",
    skill: "Localiser continents, océans, pays voisins de la France et grandes capitales.",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "hg-ge-espaces-urbains",
    title: "Comprendre les espaces urbains",
    domain: "Géographie",
    subdomain: "Organisation des espaces",
    skill: "Décrire la structure et les fonctions d'un espace urbain à différentes échelles.",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "hg-ge-espaces-ruraux",
    title: "Comprendre les espaces ruraux",
    domain: "Géographie",
    subdomain: "Organisation des espaces",
    skill: "Décrire les caractéristiques et les évolutions récentes d'un espace rural.",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "hg-ge-mobilites",
    title: "Identifier les mobilités",
    domain: "Géographie",
    subdomain: "Mobilités et transports",
    skill: "Comprendre les différents types de mobilités humaines (quotidienne, résidentielle, internationale).",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "hg-ge-reseaux-transport",
    title: "Comprendre les réseaux de transport",
    domain: "Géographie",
    subdomain: "Mobilités et transports",
    skill: "Décrire les grands réseaux de transport en France et leur organisation.",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "hg-ge-espaces-productifs",
    title: "Découvrir les espaces productifs",
    domain: "Géographie",
    subdomain: "Organisation des espaces",
    skill: "Identifier différents types d'espaces de production (industriels, agricoles, touristiques).",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "hg-ge-developpement-durable",
    title: "Comprendre les enjeux du développement durable",
    domain: "Géographie",
    subdomain: "Environnement et développement durable",
    skill: "Expliquer ce qu'est le développement durable et identifier des exemples d'actions concrètes.",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "hg-ge-documents-geo",
    title: "Lire et comparer des documents géographiques",
    domain: "Géographie",
    subdomain: "Lecture de cartes",
    skill: "Analyser et mettre en relation plusieurs documents géographiques (cartes, graphiques, photos).",
    status: "upcoming",
    level: "CM2",
  },
];

// ── Sciences ──────────────────────────────────────────────────────────────────

const sciencesSequences: Cm2Sequence[] = [
  // Démarche d'investigation
  {
    slug: "sc-di-observer-decrire",
    title: "Observer et décrire sans interpréter",
    domain: "Sciences et technologie",
    subdomain: "Démarche d'investigation",
    skill: "Formuler une observation factuelle sans l'expliquer prématurément.",
    status: "in-progress",
    level: "CM2",
    shortDescription: "Distinguer ce qu'on voit de ce qu'on suppose.",
    felixRole: "Scientifique qui consigne ses observations avant de conclure.",
    visualToCreate: "Tableau : observation / hypothèse / conclusion",
  },
  {
    slug: "sc-di-formuler-hypothese",
    title: "Formuler une hypothèse scientifique",
    domain: "Sciences et technologie",
    subdomain: "Démarche d'investigation",
    skill: "Proposer une explication provisoire vérifiable à partir d'une observation.",
    status: "upcoming",
    level: "CM2",
    teacherReference: "Différence entre hypothèse et explication définitive",
    felixRole: "Chercheur qui propose une idée à tester avant de conclure.",
    visualToCreate: "Fiche : « Je suppose que… parce que j'observe… »",
  },
  {
    slug: "sc-di-comparer-resultats",
    title: "Comparer des résultats pour dégager une conclusion",
    domain: "Sciences et technologie",
    subdomain: "Démarche d'investigation",
    skill: "Analyser plusieurs résultats en les comparant pour formuler une conclusion.",
    status: "upcoming",
    level: "CM2",
    felixRole: "Analyste qui compare deux situations pour isoler la variable.",
    visualToCreate: "Tableau comparatif : condition A vs condition B → conclusion",
  },
  {
    slug: "sc-di-rediger-conclusion",
    title: "Rédiger une conclusion scientifique",
    domain: "Sciences et technologie",
    subdomain: "Communication scientifique",
    skill: "Écrire une conclusion courte ancrée dans les résultats observés.",
    status: "upcoming",
    level: "CM2",
    teacherReference: "Structure : observation → résultat → conclusion prudente",
    felixRole: "Rédacteur du rapport final de l'expédition.",
    visualToCreate: "Modèle de phrase : « D'après les résultats… on peut conclure que… »",
  },

  // Le vivant
  {
    slug: "sc-vi-conditions-germination",
    title: "Identifier les conditions nécessaires à la germination",
    domain: "Sciences et technologie",
    subdomain: "Le vivant",
    skill: "Relier les conditions expérimentales à la présence ou l'absence de germination.",
    status: "upcoming",
    level: "CM2",
    felixRole: "Naturaliste qui observe ses graines en laboratoire.",
    visualToCreate: "Tableau : condition → résultat observé",
  },

  // Le vivant — besoins et fonctions
  {
    slug: "sc-vi-besoins-vivants",
    title: "Comprendre les besoins des êtres vivants",
    domain: "Sciences et technologie",
    subdomain: "Le vivant",
    skill: "Identifier les besoins vitaux communs à tous les êtres vivants (eau, nourriture, air).",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "sc-vi-relations-alimentaires",
    title: "Identifier les relations alimentaires",
    domain: "Sciences et technologie",
    subdomain: "Le vivant",
    skill: "Représenter et analyser des chaînes et des réseaux alimentaires.",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "sc-vi-digestion",
    title: "Comprendre la digestion",
    domain: "Sciences et technologie",
    subdomain: "Corps humain",
    skill: "Décrire le trajet des aliments et le rôle des organes digestifs.",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "sc-vi-respiration",
    title: "Comprendre la respiration",
    domain: "Sciences et technologie",
    subdomain: "Corps humain",
    skill: "Décrire le mécanisme de la respiration et le rôle des poumons.",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "sc-vi-circulation",
    title: "Comprendre la circulation sanguine",
    domain: "Sciences et technologie",
    subdomain: "Corps humain",
    skill: "Expliquer simplement le rôle du cœur et la circulation du sang dans l'organisme.",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "sc-vi-sante",
    title: "Adopter des comportements favorables à la santé",
    domain: "Sciences et technologie",
    subdomain: "Corps humain",
    skill: "Identifier des règles d'hygiène, d'alimentation équilibrée et d'activité physique.",
    status: "upcoming",
    level: "CM2",
  },

  // Matière et énergie
  {
    slug: "sc-ma-transformations",
    title: "Comprendre la matière et ses transformations",
    domain: "Sciences et technologie",
    subdomain: "Matière et énergie",
    skill: "Distinguer les états de la matière et décrire leurs changements d'état.",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "sc-en-sources",
    title: "Comprendre les sources et formes d'énergie",
    domain: "Sciences et technologie",
    subdomain: "Matière et énergie",
    skill: "Identifier les sources d'énergie renouvelables et non renouvelables et leurs usages.",
    status: "upcoming",
    level: "CM2",
  },

  // Technologie
  {
    slug: "sc-tech-objets-fonctions",
    title: "Identifier des objets techniques et leurs fonctions",
    domain: "Sciences et technologie",
    subdomain: "Technologie",
    skill: "Décrire la fonction d'un objet technique et identifier ses composants principaux.",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "sc-tech-concevoir",
    title: "Concevoir ou améliorer un objet technique simple",
    domain: "Sciences et technologie",
    subdomain: "Technologie",
    skill: "Proposer et réaliser une amélioration fonctionnelle d'un objet technique simple.",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "sc-di-demarche-complete",
    title: "Adopter une démarche scientifique complète",
    domain: "Sciences et technologie",
    subdomain: "Démarche d'investigation",
    skill: "Enchaîner toutes les étapes de la démarche : observation, hypothèse, expérience, conclusion.",
    status: "upcoming",
    level: "CM2",
  },
];

// ── EMC ───────────────────────────────────────────────────────────────────────

const emcSequences: Cm2Sequence[] = [
  {
    slug: "emc-argumenter-point-de-vue",
    title: "Exprimer et défendre un point de vue",
    domain: "EMC",
    subdomain: "Expression et argumentation",
    skill: "Formuler un point de vue personnel en l'appuyant sur des arguments.",
    status: "upcoming",
    level: "CM2",
    felixRole: "Débatteur qui respecte les règles de la discussion.",
    visualToCreate: "Fiche : point de vue + argument + exemple",
  },
  {
    slug: "emc-respecter-regles-vie",
    title: "Comprendre l'utilité des règles de vie collective",
    domain: "EMC",
    subdomain: "Vie collective et règles",
    skill: "Expliquer pourquoi des règles communes sont nécessaires dans un groupe.",
    status: "upcoming",
    level: "CM2",
    felixRole: "Médiateur qui explique les règles de l'Académie.",
    visualToCreate: "Fiche : règle → pourquoi elle existe → ce qu'elle protège",
  },
  {
    slug: "emc-distinguer-droits-devoirs",
    title: "Distinguer droits et devoirs du citoyen",
    domain: "EMC",
    subdomain: "Valeurs de la République",
    skill: "Identifier ce que la République garantit et ce qu'elle demande.",
    status: "upcoming",
    level: "CM2",
    felixRole: "Citoyen de l'Académie qui connaît ses droits et ses responsabilités.",
    visualToCreate: "Tableau : droits / devoirs / valeurs associées",
  },
  {
    slug: "emc-valeurs-republique",
    title: "Comprendre les valeurs de la République",
    domain: "EMC",
    subdomain: "Valeurs de la République",
    skill: "Expliquer les trois valeurs républicaines et les relier à des situations concrètes.",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "emc-symboles-republique",
    title: "Connaître les symboles de la République",
    domain: "EMC",
    subdomain: "Valeurs de la République",
    skill: "Identifier et expliquer les principaux symboles de la République française (drapeau, hymne, Marianne…).",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "emc-debattre-respect",
    title: "Débattre avec respect",
    domain: "EMC",
    subdomain: "Expression et argumentation",
    skill: "Participer à un débat en respectant les règles de prise de parole et d'écoute.",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "emc-cooperer-projet",
    title: "Coopérer dans un projet collectif",
    domain: "EMC",
    subdomain: "Vie collective et règles",
    skill: "Collaborer avec des pairs en tenant un rôle défini dans un projet commun.",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "emc-lutter-discriminations",
    title: "Lutter contre les discriminations",
    domain: "EMC",
    subdomain: "Respecter autrui",
    skill: "Reconnaître une discrimination, en comprendre les mécanismes et adopter une posture de refus.",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "emc-egalite-filles-garcons",
    title: "Comprendre l'égalité filles-garçons",
    domain: "EMC",
    subdomain: "Respecter autrui",
    skill: "Identifier les stéréotypes de genre et comprendre le principe d'égalité entre filles et garçons.",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "emc-jugement-critique",
    title: "Exercer son jugement critique",
    domain: "EMC",
    subdomain: "Expression et argumentation",
    skill: "Distinguer une information vérifiée d'une rumeur ou d'une opinion et justifier son jugement.",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "emc-responsabilite-internet",
    title: "Adopter un comportement responsable sur Internet",
    domain: "EMC",
    subdomain: "Citoyenneté numérique",
    skill: "Identifier les risques en ligne et adopter des comportements sûrs et respectueux.",
    status: "upcoming",
    level: "CM2",
  },
];

// ── Arts plastiques ───────────────────────────────────────────────────────────

const artsSequences: Cm2Sequence[] = [
  {
    slug: "ar-ex-techniques-variees",
    title: "Expérimenter des techniques variées",
    domain: "Arts plastiques",
    subdomain: "Techniques plastiques",
    skill: "Utiliser au moins deux techniques différentes (dessin, peinture, collage, modelage) dans une production.",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "ar-ex-composition",
    title: "Organiser une composition",
    domain: "Arts plastiques",
    subdomain: "Techniques plastiques",
    skill: "Agencer les éléments d'une image (plan, cadrage, équilibre) pour produire un effet voulu.",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "ar-prod-intention",
    title: "Produire une œuvre avec une intention",
    domain: "Arts plastiques",
    subdomain: "Création",
    skill: "Formuler une intention artistique avant de créer et la réaliser avec les moyens plastiques choisis.",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "ar-obs-analyser",
    title: "Analyser une œuvre",
    domain: "Arts plastiques",
    subdomain: "Regard sur les œuvres",
    skill: "Décrire et interpréter une œuvre d'art en utilisant le vocabulaire de l'analyse visuelle.",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "ar-pres-demarche",
    title: "Présenter une démarche artistique",
    domain: "Arts plastiques",
    subdomain: "Présentation",
    skill: "Expliquer oralement ses choix plastiques et la démarche qui a conduit à sa production.",
    status: "upcoming",
    level: "CM2",
  },
];

// ── Éducation musicale ────────────────────────────────────────────────────────

const educationMusicaleSequences: Cm2Sequence[] = [
  {
    slug: "mu-chanter-precision",
    title: "Chanter avec précision et intention",
    domain: "Éducation musicale",
    subdomain: "Voix et chant",
    skill: "Interpréter une chanson en respectant la mélodie, le rythme et en y apportant une intention expressive.",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "mu-production-collective",
    title: "Tenir sa place dans une production collective",
    domain: "Éducation musicale",
    subdomain: "Voix et chant",
    skill: "Chanter ou jouer en groupe en maintenant sa partie sans perturber l'ensemble.",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "mu-parametres-son",
    title: "Identifier des paramètres du son",
    domain: "Éducation musicale",
    subdomain: "Culture musicale",
    skill: "Reconnaître et nommer les paramètres du son (hauteur, durée, intensité, timbre) à l'écoute.",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "mu-comparer-oeuvres",
    title: "Comparer des œuvres musicales",
    domain: "Éducation musicale",
    subdomain: "Culture musicale",
    skill: "Établir des ressemblances et des différences entre plusieurs extraits musicaux en argumentant.",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "mu-ressenti-argumente",
    title: "Exprimer un ressenti argumenté",
    domain: "Éducation musicale",
    subdomain: "Culture musicale",
    skill: "Formuler à l'écrit ou à l'oral une réaction personnelle sur une œuvre écoutée, en la justifiant.",
    status: "upcoming",
    level: "CM2",
  },
];

// ── EPS ───────────────────────────────────────────────────────────────────────

const epsSequences: Cm2Sequence[] = [
  {
    slug: "ep-perf-mesure",
    title: "Produire une performance mesurée",
    domain: "EPS",
    subdomain: "Athlétisme",
    skill: "Réaliser une performance individuelle mesurable (course, saut, lancer) et comparer ses résultats.",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "ep-perf-athletisme",
    title: "Progresser dans une activité athlétique",
    domain: "EPS",
    subdomain: "Athlétisme",
    skill: "Identifier ses points d'amélioration dans une activité athlétique et mettre en œuvre un plan de progrès.",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "ep-coop-jeu-collectif",
    title: "Coopérer et s'opposer dans un jeu collectif",
    domain: "EPS",
    subdomain: "Jeux collectifs",
    skill: "Élaborer une stratégie collective, la communiquer à l'équipe et l'appliquer en situation de jeu.",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "ep-coop-regles-roles",
    title: "Respecter règles, rôles et arbitrage",
    domain: "EPS",
    subdomain: "Jeux collectifs",
    skill: "Appliquer les règles d'un jeu, accepter différents rôles (joueur, arbitre, observateur) et arbitrer soi-même.",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "ep-expr-prestation-corporelle",
    title: "Réaliser une prestation corporelle",
    domain: "EPS",
    subdomain: "Activités artistiques et acrobatiques",
    skill: "Composer et présenter devant un public une séquence dansée ou acrobatique mémorisée.",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "ep-dep-adapter",
    title: "Adapter ses déplacements à différents environnements",
    domain: "EPS",
    subdomain: "Déplacements en milieux variés",
    skill: "Modifier ses appuis et son allure en fonction des contraintes du milieu (obstacles, pente, eau).",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "ep-proj-collectif",
    title: "Construire un projet collectif en EPS",
    domain: "EPS",
    subdomain: "Jeux collectifs",
    skill: "Participer à l'élaboration d'un projet d'équipe, définir des rôles et évaluer les progrès collectifs.",
    status: "upcoming",
    level: "CM2",
  },
];

// ── Anglais ───────────────────────────────────────────────────────────────────

const anglaisSequences: Cm2Sequence[] = [
  {
    slug: "an-co-comprendre-oral",
    title: "Comprendre des messages simples à l'oral",
    domain: "Anglais",
    subdomain: "Compréhension orale",
    skill: "Comprendre un message oral simple énoncé clairement et lentement sur un sujet familier.",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "an-co-repondre-questions",
    title: "Répondre à des questions simples",
    domain: "Anglais",
    subdomain: "Compréhension orale",
    skill: "Répondre brièvement à des questions simples posées par l'enseignant en anglais.",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "an-lex-quotidien",
    title: "Utiliser le vocabulaire du quotidien",
    domain: "Anglais",
    subdomain: "Lexique",
    skill: "Mémoriser et utiliser un vocabulaire de base sur des thèmes courants (famille, école, animaux, couleurs).",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "an-ce-comprendre-texte",
    title: "Lire et comprendre un texte court en anglais",
    domain: "Anglais",
    subdomain: "Compréhension écrite",
    skill: "Comprendre le sens général d'un texte court en s'aidant du contexte et des mots connus.",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "an-po-presenter",
    title: "Se présenter à l'oral en anglais",
    domain: "Anglais",
    subdomain: "Expression orale",
    skill: "Dire son nom, son âge, sa nationalité et ses goûts en utilisant des structures simples.",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "an-po-decrire-environnement",
    title: "Décrire son environnement en anglais",
    domain: "Anglais",
    subdomain: "Expression orale",
    skill: "Décrire sa maison, son école et ses activités quotidiennes à l'aide de phrases simples.",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "an-gram-structures-simples",
    title: "Utiliser des structures grammaticales simples de base",
    domain: "Anglais",
    subdomain: "Grammaire",
    skill: "Employer correctement le présent simple, les pronoms personnels et les articles en contexte.",
    status: "upcoming",
    level: "CM2",
  },
  {
    slug: "an-cult-decouvrir",
    title: "Découvrir des éléments culturels anglophones",
    domain: "Anglais",
    subdomain: "Culture",
    skill: "Identifier des caractéristiques culturelles de pays anglophones (fêtes, traditions, géographie).",
    status: "upcoming",
    level: "CM2",
  },
];

// ── Registre complet ──────────────────────────────────────────────────────────

export const cm2Sequences: Cm2Sequence[] = [
  ...francaisSequences,
  ...mathematiquesSequences,
  ...histoireGeoSequences,
  ...sciencesSequences,
  ...emcSequences,
  ...artsSequences,
  ...educationMusicaleSequences,
  ...epsSequences,
  ...anglaisSequences,
];

// ── Accesseurs ────────────────────────────────────────────────────────────────

export function getCm2SequencesByDomain(domain: string): Cm2Sequence[] {
  return cm2Sequences.filter((s) => s.domain === domain);
}

export function getCm2SequencesBySubjectAndStatus(
  subjectSlug: string,
  status: Cm2SequenceStatus,
): Cm2Sequence[] {
  return cm2Sequences.filter(
    (s) =>
      slugMatchesSubject(s, subjectSlug) && s.status === status,
  );
}

export function getCm2SequencesBySubjectSlug(subjectSlug: string): Cm2Sequence[] {
  return cm2Sequences.filter((s) => slugMatchesSubject(s, subjectSlug));
}

export function getCm2SequenceBySlug(slug: string): Cm2Sequence | undefined {
  return cm2Sequences.find((s) => s.slug === slug);
}

function slugMatchesSubject(seq: Cm2Sequence, subjectSlug: string): boolean {
  const prefixMap: Record<string, string[]> = {
    francais: ["fr-"],
    mathematiques: ["ma-"],
    "histoire-geographie": ["hg-"],
    sciences: ["sc-"],
    emc: ["emc-"],
    arts: ["ar-", "mu-"],
    eps: ["ep-"],
    anglais: ["an-"],
  };
  const prefixes = prefixMap[subjectSlug] ?? [];
  return prefixes.some((p) => seq.slug.startsWith(p));
}

// ── Statistiques de pilotage ──────────────────────────────────────────────────

export function getCm2SequencesStats() {
  const total = cm2Sequences.length;
  const available = cm2Sequences.filter((s) => s.status === "available").length;
  const inProgress = cm2Sequences.filter((s) => s.status === "in-progress").length;
  const upcoming = cm2Sequences.filter((s) => s.status === "upcoming").length;
  return { total, available, inProgress, upcoming };
}
